### ISSUE TITLE
Readonly

### ISSUE THREAD

**Issue by Cirrusware** [koumoul-dev/vuetify-jsonschema-form#10]
Hello,

First thanks for this lib.

How add a readonly input ?
I find accordion to group by fields, but have you the same thing with  v-tabs ?  
Can we put the fields in columns ?

Vincent

**Comment by albanm** [comment]
Hello,

Sorry for the delay, I totally forgot about this issue.

  - no disabled field for now, only a disableAll global option and x-display=hidden on properties, could be done
  - no use of v-tabs and no column layouts either, less easy to do
