### ISSUE TITLE
Duplicate field for date-time

### ISSUE THREAD

**Issue by rakanalh** [koumoul-dev/vuetify-jsonschema-form#11]
Hello

Using the date or date-time fields would result in two "input boxes" being rendered. Not sure what the purpose of the second field, is there a way to hide or get rid of the other one?

![DeepinScreenshot_select-area_20190418222827](https://user-images.githubusercontent.com/195829/56389244-5756d380-6229-11e9-9fe9-bce60c520813.png)

Thanks

**Comment by albanm** [comment]
Thanks for the bug report. This is fixed in 0.25.1 that I just published.
