### ISSUE TITLE
How to determine the icon in an iconOneOf?

### ISSUE THREAD

**Issue by jhhammer** [koumoul-dev/vuetify-jsonschema-form#110]
Regarding example **Select with icons** the schema for a oneOf with icons looks like:
```javascript
iconOneOf": {
      "title": "I'm a select with icon codes and titles in a oneOf",
      "type": "string",
      "x-display": "icon",
      "oneOf": [
        {
          "const": "mdi-alarm",
          "title": "Alarm",
          "icon": "mdi-alarm"
        },
        {
          "const": "mdi-alarm-plus",
          "title": "Alarm plus",
          "icon": "mdi-alarm-plus"
        }
      ]
    }
```
How do I change the icon? I thought this would be straight forward by simply changing property `icon`. But unfortunately property `const` determines the icon and property `icon` can be deleted. What do I miss? How is it intended to be?

**Comment by jhhammer** [comment]
I think this is a bug!

**Comment by albanm** [comment]
Not really a bug, but a mistake in the doc.

By default the icon code is taken in the value of the property (here const), to use the secondary attribute "icon" or any other you must use "x-itemIcon": "icon".

Sorry for the delay.

**Comment by jhhammer** [comment]
Nice! Thank you!
