### ISSUE TITLE
Setting default values

### ISSUE THREAD

**Issue by jhhammer** [koumoul-dev/vuetify-jsonschema-form#112]
Is it possible to set default values. If e.g. in a oneOf-select an item is selected and I want the model of this item to contain default values. What is the best way to achieve this?

**Comment by albanm** [comment]
The [default](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.2) keyword of JSON schema is supported (or should be, tests are not exhaustive). Is this what you mean ?

**Comment by jhhammer** [comment]
Yes and it works.

**Comment by jhhammer** [comment]
Is this somewhere described in the documentation?

**Comment by albanm** [comment]
Just added this example https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#default-values
