### ISSUE TITLE
third-party.js:517 Uncaught ReferenceError: Vue is not defined

### ISSUE THREAD

**Issue by clarkekawakami** [koumoul-dev/vuetify-jsonschema-form#113]
1. Use vue cli 4.1.2 to create project : vue create vjsf_test
2. install vuetify plugin: vue add vuetify
3. install vuetify-jsonschema-form : npm install @koumoul/vjsf
4. add imports to HelloWorld.vue (file attached)
5. compiles OK
6. open in Chrome http://localhost:8080/
7. browser console displays subject error (screenshot attached)
[vjsf.zip](https://github.com/koumoul-dev/vuetify-jsonschema-form/files/4786682/vjsf.zip)
![Screen Shot 2020-06-16 at 8 47 43 AM](https://user-images.githubusercontent.com/1221212/84776752-b7244800-afae-11ea-91b0-e0115221ac0e.png)

**Comment by jhhammer** [comment]
Did you try this https://github.com/koumoul-dev/vuetify-jsonschema-form/issues/89#issuecomment-632694855

**Comment by clarkekawakami** [comment]
> Did you try this [#89 (comment)](https://github.com/koumoul-dev/vuetify-jsonschema-form/issues/89#issuecomment-632694855)

Thanks for you reply but I still am not able to get this going.

**Comment by albanm** [comment]
Sorry for the lack of response. I wanted to look into this sometime in the next few days.

Can you tell me why you closed the issue ? Did you find a solution, did you give up ?

**Comment by clarkekawakami** [comment]
I stumbled around until I found enough information to get a (at least basic types) form working in a nuxt app (but still not a vue cli app) by just commenting out the third-party import. I will be playing with this more over the next few days to see if this will meet the requirements of my application.

I am new to Vue... what would really help me (and I suppose people like me) is a step by step that more or less follows the steps I listed in the original issue...

1. create an app with vue cli. 
2. install the required dependencies.
3. show and explain any config change requirements.
4. create a form component that uses VJsf.
5. display the form component on App.vue along with or instead of Helloworld.vue

I probably require more hand-holding than your typical user so I appreciate whatever direction you can give me. 

Thanks.

--clarke

**Comment by albanm** [comment]
I don't think I will go that far back in the process. This library is just a layer on top of vue and vuetify for some specific use cases, most users will already have a working project and basic knowledge of the underlying frameworks. Also the setup will vary from user to user.

But still I do need to make sure that everything works smoothly in a new project created by vue-cli and I will improve the getting-started.

**Comment by a0m0rajab** [comment]
@albanm 
Hey, I got the same error yet could not find a solution or understand the cause, 
I followed the getting started steps but it did not work.

**Comment by albanm** [comment]
I just added a section to the [getting started](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/getting-started/) with a simple Vue CLI based setup. Hope this helps.

**Comment by a0m0rajab** [comment]
I have checked it already but it did not work 😅

Outlook for Android<https://aka.ms/ghei36>

Abdurrahman Rajab

________________________________

**Comment by albanm** [comment]
The section "Vue CLI setup" I added only a few minutes ago at the end of the page ?

**Comment by a0m0rajab** [comment]
Okay I just read it, I have not done the  config thingy, I will update you after doing it 🤗

Thanks

Outlook for Android<https://aka.ms/ghei36>

Abdurrahman Rajab

________________________________

**Comment by a0m0rajab** [comment]
@albanm thank you, It's working now. 

in the previous setup I did add anything to the config file  - which was the cause of my problem :)
