### ISSUE TITLE
Representing multiple choice(radiogroup) and selection(checkboxgroup)

### ISSUE THREAD

**Issue by GarretBlueMango** [koumoul-dev/vuetify-jsonschema-form#114]
Hi,

I'm trying to figure out how to create a form with a radio group and checkbox group in the style of google forms. 

Question?
- [ ]  Option 1
- [ ]  Option 2
- [ ]  Option 3

**Radio group**
If I create a stringofone and set x-display:radio. I do get the oneOf items represented as radio boxes and I can only select one. But I don't get required validation feedback anymore

**checkbox group**
If I create a stringarrayofone and set x-display:checkbox.  I do get the oneOf items represented as checkboxes and I can multiple items. But also here I don't get validation feedback anymore

I tried creating custom representation with x-display and a template within the v-jsf tag, but I didn't make any progress there. 

So I hope I'm just overlooking something in the documentation or an undocumented feature, or I'm trying to do something that isn't possible yet, so then this would be a feature request

**Comment by GarretBlueMango** [comment]
Ok, I think I made a typo somewhere, but radio group is working

`                "question-1": {
                    "type": "string",
                    "title": "Do you have a question?",
                    "oneOf": [
                        {
                            "const": "c7a15225-31df-427b-af03-b0d4004116a4",
                            "title": "Yes"
                        },
                        {
                            "const": "76dec783-5b84-410f-972c-81fe0dd2367d",
                            "title": "No"
                        }
                    ],
                    
                    "x-display": "radio"
                },`

is working, and also gives me validation feedback.

For checkbox still no luck

**Comment by albanm** [comment]
The functionality is partially implemented thanks to a pull request I merged a few weeks ago. But it is not complete and not documented.

I am working on it right now. The target is to be able to use all selection controls (radio, checkbox, switch) in groups with single or multiple values. I think it will be ready in a few days, end of the week max.

**Comment by albanm** [comment]
Is this ok ? https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#selection-controls

**Comment by GarretBlueMango** [comment]
This awesome, precisely what I was looking for thank @albanm
