### ISSUE TITLE
Implement boolean switch?

### ISSUE THREAD

**Issue by stevefan1999-personal** [koumoul-dev/vuetify-jsonschema-form#116]
I have a little schema that's copied from the documentation (to test it out of course)
```ts
import { IsBoolean, IsBooleanString, IsNotEmpty, IsString } from 'class-validator'
import { JSONSchema } from 'class-validator-jsonschema'

export class HelloWorld {
  @IsNotEmpty()
  @JSONSchema({
    description: 'This description is used as a help message',
    format: 'date',
    title: 'I\'m a simple date'
  })
  public dateProp: Date
  
  @IsNotEmpty()
  @JSONSchema({
    format: 'time',
    title: 'I\'m a simple time of day'
  })
  public timeProp: string
  
  @IsNotEmpty()
  @JSONSchema({
    format: 'date-time',
    title: 'I\'m a date with time'
  })
  public datTimeProp: Date
  
  @IsBoolean()
  @JSONSchema({
    'title': 'A boolean',
    'x-display': 'switch'
  })
  public boolean1: boolean
}
```
But I see that the `boolean1` entity didn't really have a switch over there, which is still a checkbox, and I see that only selections are allowed to have switches.

Although obviously we can work around that by set relations (e.g. we have three fields A,B,C then test their value as boolean by saying does this key `x` exist in the selection array for all x in fields), this is really cumbersome and non-ergonomic.

Also, would you like to implement Set/Map for the validation model?

**Comment by albanm** [comment]
Will be available in next release (soon, I just need to perform a few more tests before releasing potentially breaking changes).

I didn't understand your last question about validation.

**Comment by stevefan1999-personal** [comment]
> 
> 
> Will be available in next release (soon, I just need to perform a few more tests before releasing potentially breaking changes).
> 
> I didn't understand your last question about validation.

Well an array is obviously not a set so things can duplicate, and I think we could use Set in this case. This could be good to implement something like picking 3 out of 5 items, mutually exclusive item pairs etc.

**Comment by jhhammer** [comment]
Looking forward to having the possibility to use a switch instead of a checkbox for a single boolean property. When is this going to be released?

**Comment by albanm** [comment]
released, feel free to reopen if necessary
