### ISSUE TITLE
Working with type array for nullable string

### ISSUE THREAD

**Issue by kvanska** [koumoul-dev/vuetify-jsonschema-form#120]
I realized this project does not support: 

`type: ['string', 'null']`

for nullable string types. many schema generators do this by default. Should this be a feature request?

**Comment by albanm** [comment]
Yes, it seems to be a quite common practice.

But don't expect it to land very soon. It will be in at least a few weeks I think, except if a pull request is submitted.

**Comment by albanm** [comment]
Available in v1.15.0, see https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#nullable
