### ISSUE TITLE
Preserve form values when switching between sub-schemas

### ISSUE THREAD

**Issue by islandjack** [koumoul-dev/vuetify-jsonschema-form#121]
Is there a way to preserve any values entered in sub-schema form fields when switching between sub-schemas?  The model appears to contain the data entered, but the form controls are empty when switching back and forth.

**Comment by albanm** [comment]
The code that manages sub models switching, cleaning extra properties, etc, is quite complex and bug-prone. I'd rather not add complexity with this kind of cases.
