### ISSUE TITLE
Side effect of arrays: the first array value is always required?

### ISSUE THREAD

**Issue by OdiljonQurbon** [koumoul-dev/vuetify-jsonschema-form#122]
Please, see the schema in [Codepan](https://codepen.io/odiljonqurbon/pen/GRoyJPK?editors=1010)
You cannot enter value only to the second array. In model ```"odk_label": [ null, "Text B" ]``` **null** is not allowed.

**How to reproduce:** Type text into "Not required B" field

![image](https://user-images.githubusercontent.com/54809428/86351659-4a2ad680-bc6d-11ea-80a1-fe31f1ac1286.png)

**Comment by albanm** [comment]
This is a tricky one, but yes this is actually the expected behavior.

The problem is that if I was to authorize null values the produced model would not satisfy the given schema.
