### ISSUE TITLE
Add support for mdiSvg iconFont

### ISSUE THREAD

**Issue by MaximeSauvage1** [koumoul-dev/vuetify-jsonschema-form#124]
Hello there!

I'm using your library with 'mdiSvg' as iconFont for Vuetify.
The problem is that the icons are not rendered correctly.

I'm not familiar with reporting issue and contributing to projects but I investigated a little.
In the iconSets object (./utils/options) I added a 'mdiSvg' attribute but this didn't seem to solve the problem when the object is used in the computed of VJsfNoDeps...

Hope you'll find it useful to integrate in your library and thanks you for this library which saves me a lot of time and painful work :)

Max

**Comment by albanm** [comment]
Hello,

I will have a look. But FYI it won't be until a few weeks from now after my holidays, sorry about that.

**Comment by MaximeSauvage1** [comment]
Hi @albanm ,

Thanks for your reply. I'll try to found a workaround for now.

Have a nice holiday!
