### ISSUE TITLE
Disable sorting on editable array

### ISSUE THREAD

**Issue by ghost** [koumoul-dev/vuetify-jsonschema-form#126]
Is it possible to disable the <draggable> functionality on an editable array? There are scenarios where not all arrays need to be reordered.

**Comment by albanm** [comment]
Sorry for the long delay. I juste added a "disableSorting" option. You can use it globally or locally on a property with the "x-options" attribute.

**Comment by albanm** [comment]
I will probably be released in a few hours, or a few days max.

**Comment by albanm** [comment]
released, feel free to reopen if necessary
