### ISSUE TITLE
Share model between different tabs

### ISSUE THREAD

**Issue by Cirrusware** [koumoul-dev/vuetify-jsonschema-form#128]
Hello,

I would like to know if it is still impossible to share the model between several tabs.

https://codepen.io/vincefr/pen/gOPjBar

![image](https://user-images.githubusercontent.com/5724417/87338502-99161d00-c545-11ea-8f24-b36a72228040.png)

In this case, test2 overwrite data and I lost data.test1. This works fine for fields when there is no depth.

Thanks for your return.

Vincent

**Comment by albanm** [comment]
Hello,

I don't think I will support this. It is a edge case and I'm afraid of bringing more complexity in the sub-models code which is already quite complex and bug-prone.

**Comment by Cirrusware** [comment]
Hello,

On the first version (0.x), I have deploy a strategy with input change to collect each changed value in another object.
But now, I don't see this event. If you re-add this mechanics, I take it.

For me, a tabulation it's just an information display. In real life, I have many cases like this.

Thanks for yours returns and yours efforts for this good library.
