### ISSUE TITLE
Place 2 inputs on the same row

### ISSUE THREAD

**Issue by cosmyn9708** [koumoul-dev/vuetify-jsonschema-form#13]
I can't find a way to put 2 inputs on the same row. Is this supported?

**Comment by albanm** [comment]
No, it is not supported.

**Comment by cosmyn9708** [comment]
It's the only major feature that's missing. I know that Vuetify natively supports **reactive** layouts.

**Comment by albanm** [comment]
I agree, it would be a nice addition.

I need to look for the best way to express this idea in the json schema and implement it.

**Comment by manuhank** [comment]
In regard to the json expression maybe using a "cols" property, similary to the new vuetify grid system?

> Columns will automatically take up an equal amount of space within their parent container. This can be modified using the cols prop. You can also utilize the sm, md, lg, and xl props to further define how the column will be sized in different viewport sizes.

[https://vuetifyjs.com/en/components/grids](url)

**Comment by albanm** [comment]
I chose to use a simple class mechanism that should cover this need as well as others.

I used the older v-flex component instead of v-col in order to maintain compatibility with vuetify 1.

**Comment by bam-tbf** [comment]
Thank you. I recommend updating the documentation for this feature.

**Comment by albanm** [comment]
Yes, documentation is clearly lacking for this feature as well as others.

**Comment by xueyongg** [comment]
where is the documentation for this? Love to explore and implement this too!

**Comment by albanm** [comment]
This is covered here : https://koumoul-dev.github.io/vuetify-jsonschema-form/master/examples#classes

**Comment by xueyongg** [comment]
I saw it! Thank you @albanm Wish to check if this library will have Multiple choice grid as well? Something similar to multiple choice but horizontally listed
![image](https://user-images.githubusercontent.com/11015221/224964462-09187056-1f0a-467a-add9-d1be9c7d9f2d.png)
![image](https://user-images.githubusercontent.com/11015221/224964506-2875189b-a4ee-4a78-a3a2-452d2b0b070d.png)
