### ISSUE TITLE
v-aucomplete duplicate requests for items

### ISSUE THREAD

**Issue by Yolley** [koumoul-dev/vuetify-jsonschema-form#131]
In this demo https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples/#select-http

When we clear autocomplete field (the last one), it makes 2 identical requests for items.
![image](https://user-images.githubusercontent.com/13859030/88179463-a3ff3a80-cc34-11ea-84fb-2907748e3c18.png)
(They are both "GET" requests).

This also happens in my application. I am trying to investigate this, but for now I did not find the exact reason.

**Comment by albanm** [comment]
I didn't look for the exact cause, instead I applied a debounce to the request. This way quick successions of requests are prevented, which includes this specific case.

Should be released in a few hours hopefully, or a few days otherwise.

**Comment by albanm** [comment]
released, feel free to reopen if necessary
