### ISSUE TITLE
File.lastModifiedDate is deprecated

### ISSUE THREAD

**Issue by salim-dev** [koumoul-dev/vuetify-jsonschema-form#134]
Hello there !

I had a little problem with This feature in Firefox, but is no longer recommended in firefox. 
Though some browsers might still support it.

https://developer.mozilla.org/en-US/docs/Web/API/File/lastModifiedDate

https://github.com/koumoul-dev/vuetify-jsonschema-form/blob/ec0bcde2868058295a9469a8e88cc8160858122a/lib/mixins/FileProperty.js#L19
Solution :
`lastModified: new Date(file.lastModified).toISOString(), `

**Comment by albanm** [comment]
thanks
