### ISSUE TITLE
Width of Card for Editable Array

### ISSUE THREAD

**Issue by sanman-99** [koumoul-dev/vuetify-jsonschema-form#135]
First off, this package is fantastic!  I've started to implement this in one of my projects and everything is working well.  I'm trying to figure out how to set the width or max-width of a card that is generated when using the editable array so it isn't taking the whole width of the page.  I've tried using x-props, but I'm either defining it in the wrong place or using it incorrectly.  Any possible way I can get an example of how to do this using the editable array example in the documentation?

**Comment by albanm** [comment]
Thanks !

I just published a release with new option arrayItemColProps (default value is {cols: 12}) to customize the props given to the v-col component around each item of the array. I think this solves your problem, feel free to reopen the issue if necessary.
