### ISSUE TITLE
after updgrading to v1.11.0 selects from HTTP don't show selected value

### ISSUE THREAD

**Issue by kvanska** [koumoul-dev/vuetify-jsonschema-form#137]
After upgrading from v1.10.3 to v1.11.0 selects from HTTP don't show selected value when showing form with existing data. 

Selecting data for "new" item works and data is shown (and saved) correctly.

**Comment by albanm** [comment]
This example seems to work : https://codepen.io/albanm/pen/WNwpqpj

Am I missing something ?

**Comment by albanm** [comment]
Never mind, there was indeed a regression in the case where you didn't define the expected properties from the HTTP result. The children properties were removed as additional properties, it was not strictly a bad behavior but it was a breaking change.
