### ISSUE TITLE
Date Field is not displaying values when model computed

### ISSUE THREAD

**Issue by jithin-space** [koumoul-dev/vuetify-jsonschema-form#150]
When the model is a computed property, the date fields are not displaying the selected values. How can I fix that??

**Comment by albanm** [comment]
Having a computed property as the model is weird no ? I guess it can make sense to display a fully read-only form. Still v-jsf expects a model that it can mutate, so a data property not a computed property.

**Comment by jithin-space** [comment]
I am trying to generate an editable form filled with values from the database. data is stored in vuex, and had to do some preprocessing to convert the data into a form that vjsf can render properly. 

Are you saying that such use cases cannot be handled effectively??

**Comment by albanm** [comment]
No it can be done of course. But you must process the model then put it in a data property, not use a computed property. This is not a problem with this library, but with how to use vuejs. The computed properties are not meant to be mutated directly.
