### ISSUE TITLE
how to access key within object using x-fromUrl select

### ISSUE THREAD

**Issue by parichay0009** [koumoul-dev/vuetify-jsonschema-form#151]
My schema is: 
schema = {
	type: 'object',
	properties: {
		
		selectAjaxWithQuery: {
			type: 'object',
      properties:{
        result2:{
          type:'array'
        }
      },
			title: 'I\'m an object from a HTTP request with query',
			'x-fromUrl': 'http://example.com/api?qry="tst'',
      'x-itemsProp': 'result',
			
		}
        }
}

and response from api call is : 
{"result":{
"result2":[]
}}

how to render result2 in select component.
i m getting Result of http fetch 'http://example.com/api?qry="tst'' is not an array

**Comment by albanm** [comment]
The library is quite limited in the way it can read results from an HTTP request, the array of items can be the root of the data or a sub-property, but nothing more complicated. I suppose I could implement a deeper property reading (probably x-itemsProp="result.result2"), but it is not supported for now.

In the meantime, you could write an interceptor that transforms the response, and add it to a HTTP client that you then pass as the httpLib option.
