### ISSUE TITLE
Add support for "examples" from draft-6 as combobox

### ISSUE THREAD

**Issue by jousepo** [koumoul-dev/vuetify-jsonschema-form#156]
In order to improve the capabilities of the library it would be interesting the inclusion of the **examples** keyword from the #draft-6 of the json-schema specification.
I've implemented this using custom slots as a **combobox** were you can write anything in value but it's suggested the "examples" values.
Resuming... the same you implemented for _enum_ but using **comobox** instead of **autocomplete**.

Reference: https://json-schema.org/understanding-json-schema/reference/generic.html#annotations

**Comment by albanm** [comment]
Good idea, I will do this or gladly accept a pull request.

**Comment by jousepo** [comment]
Ok!! I'll send the pull request as soon as possible.

**Comment by jousepo** [comment]
Pull request sent!!!

This is a preview of the included doc running...
![image](https://user-images.githubusercontent.com/29270718/93753440-71f06180-fc00-11ea-9c44-43d73edc2c42.png)
