### ISSUE TITLE
Creating dropdown for Name-Value pair?

### ISSUE THREAD

**Issue by glikoz** [koumoul-dev/vuetify-jsonschema-form#16]
It is so common scenario, you have item list, all of them are complex objects (each item has Name and Value property)
End-user sees Name Property on DropDown.
But we save Value property at the back-end (json result)

Is there any way to implement it, I tried so many combinations with object,array, enum. But all of them failed.
Thanks.

**Comment by albanm** [comment]
Have a look at the line "From oneOf" in the example "Selects" of the [demo page](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/).

Please close the issue if this answers your question.

**Comment by glikoz** [comment]
Sorry, I recognized now, Thx, definetly it solves my problem.
