### ISSUE TITLE
Request: Remove default setting of v-textarea filled property

### ISSUE THREAD

**Issue by Marqzman1221** [koumoul-dev/vuetify-jsonschema-form#163]
Hi there.

Just started using your component and its coming in really handy. However I have issue with the fact that `v-textarea` field has it's `filled` property set to true by default. In my use case, I need it to not be filled in order to be consistent with other uses of `v-textarea` in my application, and I am not able to set filled to false using `x-props` or `fieldProps`. 

Here is a [Codepen ](https://codepen.io/Marqzman1221/pen/vYGMPeO) for a simple example.

Is it possible for this minor thing to be changed? Or maybe I can do what I want and I'm missing something. Would love some input, thanks!

**Comment by albanm** [comment]
Hello,

Indeed there is a mistake, filled is always added to props for the v-textarea component. This needs to be configurable, I will fix it soon.

**Comment by Marqzman1221** [comment]
Awesome! Thank you so much for the quick response!

**Comment by albanm** [comment]
Fixed and released in v1.14.0. You can override default textarea props using the textareProps option whose  default value is {filled: true}.

**Comment by Marqzman1221** [comment]
That's great thank you so much! You're a hero for the quick turn around!
