### ISSUE TITLE
Empty fields not being included in the model

### ISSUE THREAD

**Issue by Marqzman1221** [koumoul-dev/vuetify-jsonschema-form#166]
Hey there. I'm curious about a behavior of the model object that is passed to the vjsf component. I notice that any field that is blank isn't included in the model. Meaning in my use case that I have this issue:

1. Data set is loaded from a database.
2. Data set is passed as model to vjsf component.
3. User clears a field and submits model to update database record.
4. Since the cleared field is no longer included in the model, said field is not updated in database.

Here is a [Codepen](https://codepen.io/Marqzman1221/pen/GRqgYgJ) to better illustrate this. 

Is this behavior intended? Is it possible to change this behavior? If not, would it be possible to add an option to circumvent this behavior?

**Comment by albanm** [comment]
This behavior is intended, there is not always an obvious value for a cleared field.

I think I need to implement the "null" type (see https://github.com/koumoul-dev/vuetify-jsonschema-form/issues/120), clearing a field with "null" type would result in storing a null value. It can't be done without the null type as the model would not be valid against the schema.

**Comment by albanm** [comment]
Please check if this could work for you : https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#nullable

**Comment by Marqzman1221** [comment]
Yes that does work! Cool to see this was resolved thanks to v1.15. Thank you for the continued help and development!
