### ISSUE TITLE
Hello,could you please tell me how to edit jsonschema without brace？

### ISSUE THREAD

**Issue by radiorz** [koumoul-dev/vuetify-jsonschema-form#170]

**Comment by albanm** [comment]
JSON schema is JSON, so the braces are required, but you can write in another format like YAML then convert to JSON.

**Comment by radiorz** [comment]
thanks,so can i use YAML in vue.js or vuetify project

**Comment by albanm** [comment]
These are 2 independant things. Vue and vuetify do not know yaml, they only know js objects and variables, but it is up to you to use a yaml parsing library beforehand to process your schemas if you prefer the yaml syntax over the usual JSON syntax.

**Comment by radiorz** [comment]
fine，now i use vue-cli-plugin-yaml to import my .yml files.thanks a lot
