### ISSUE TITLE
Allow to hide/show inputs when a boolean is toggled

### ISSUE THREAD

**Issue by sobrinho** [koumoul-dev/vuetify-jsonschema-form#175]
Let's say I have this form:

```
[ ] Enable SMS? (Boolean)
[ ] Phone Number Required (Boolean)
```

But I only want to present the `Phone Number Required` when the `Enable SMS` is true because otherwise, the input doesn't make sense.

My first thought at schema level would be something like:

```json
"enable_sms": {
  "type": "boolean"
},
"require_phone_number": {
  "type": "boolean",
  "x-render-only-if": "enable_sms"
}
```

Or something in that sense, the property would specify the one that needs to be "true" to render it.

_I'm simplifying here with two inputs but our case includes half a dozen fields that could be hidden._

**Comment by datenspast** [comment]
I`m currently struggling also with conditional display of items in the form. 
I would also appreciate a simpler way of doing this. In particular with custom conditions in number fields e.g. display a form or section if a value is higher than x.

I think you can solve your problem by:
``` javascript
 schema:{
        "type": "object",
        "properties": {
            "booleanProp": {
                "type": "boolean",
                "title": "Enable SMS?",
                "description": "This description is used as a help message."
            },
        },
        "dependencies": {
            "booleanProp": {
            "properties": {
                "booleanSwitchProp": {
                    "type": "boolean",
                    "title": "Phone Number Required ",
                    "description": "This description is used as a help message."
                },
                
            }   
            }
        }       
    },
```

**Comment by albanm** [comment]
Yes that is the idea, I try to stick with JSON schema (http://json-schema.org/understanding-json-schema/reference/object.html#schema-dependencies) as much as possible and not add too many extra keywords.

But I realize that this functionality is not very intuitive, it is also possible that it is not semantically correct as the spec says that it is the presence of the property that should matter while I use a "truthy" evaluation. For this reason I didn't write an example with boolean dependencies, and I really should take more time to think about this use case.

**Comment by albanm** [comment]
I need to look more closely at [this](https://json-schema.org/understanding-json-schema/reference/conditionals.html), I think it could solve this use-case and more. My problem is that it would necessitate adding ajv or another validation tool as a dependency to vjsf, I don't want to bloat the lib.

**Comment by datenspast** [comment]
Support for conditional applying subschemas would be great. Anyhow, thanks for the great library!

Not sure if this is constructive: 
I looked at this example, where you used the value of another property: https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#select-deps

`"x-fromUrl": "{selectAjaxObject.href}/schema",`

Would it be possible to evaluate properties in the "x-display" to decide if the item is visible or even specify a new one, like x-visible?

**Comment by albanm** [comment]
If I understand what your are saying that would require implementing some sort of expression language. I'd rather look into conditional schemas, in this case the expression language is JSON schema itself.

**Comment by sobrinho** [comment]
Maybe if VJSF allows us to implement a custom render for inputs, we could handle that and other use cases as well, i.e.:

```vue
  <vjsf :schema="schema" :model="model">
    <template slot="default" slot-scope="{modelKey, value, attributeSchema}">
      <vjsf :schema="childSchema" v-if="attributeSchema.dependsOn ? !!model[attributeSchema.dependsOn] : true" />
    </template>
  </vsjf>
```

Let's say a slot that allows me to replace the input, then I could access the attribute schema and check if there is a key that I name whatever and then I do my logic (no matter what it is, could be hiding, disabling/enabling, etc).

If the key I'm expecting to define whatever the logic is not there, I can simply ask VJSF to keep rendering as usual.

While this can be really powerful can be messy if not used properly but that way I could do anything with the inputs that the library itself does not need to have.

All of that encapsulated in a "custom VJSF" component and that's it!

**Comment by albanm** [comment]
If I am not mistaken what you describe is already possible, I suppose you could use a vjsf instance inside a slot of another one (https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#slots-wrappers) and use your own logic around it. But honestly I wouldn't go too far in this direction, things could get real messy and you would probably end up giving me a headache with very complicated issues ! Feel free to try anyway of course.

**Comment by sobrinho** [comment]
How could I render the input as VJSF would do without any intervention?

Let's say:

```vue
<vjsf :schema="schema" :model="model">
  <template slot="default" slot-scope="slotScope">
    <vjsf-input v-bind="slotScope" />
  </template>
</vsjf>
```

Something like that.

**Comment by albanm** [comment]
No the context passed to slots does not match exactly with the expected parameters of v-jsf. You can display slotScope to see what is in it.

It would look more like this, with probably some missing stuff:

```vue
<vjsf :schema="schema" v-model="model">
  <template slot="myProp" slot-scope="{value, schema, input, change}">
    <vjsf-input :value="value" :schema="schema" @input="input" @change="change" />
  </template>
</vsjf>
```

**Comment by albanm** [comment]
I just published the conditional subschema functionality, please have a look [here](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#conditionals).

I marked it as beta as I still need to think about it and maybe reconsider the implementation. But for simple use-cases like a boolean switch it is safe to use it.

**Comment by sobrinho** [comment]
@albanm the idea of using a prop in the attribute itself seems more appropriate because that way we can't add fields after the optional props, i.e.: https://codepen.io/gcsobrinho/pen/eYdbdZm?editors=101

**Comment by albanm** [comment]
Yes, fine control of the order of the properties is a recurring problem. In this case I would make a similar recommendation as the JSON [schema spec](https://json-schema.org/understanding-json-schema/reference/conditionals.html).

> Unfortunately, this approach above doesn’t scale to more than two countries. You can, however, wrap pairs of if and then inside an allOf to create something that would scale.

Splitting the schema using allOf brings a lot of possibilities. I updated the [example in branch master](https://github.com/koumoul-dev/vuetify-jsonschema-form/commit/c7eb47bb4206fb015af8c24c13b333f1b2a4d8c5) to illustrate this.

**Comment by sobrinho** [comment]
Still feel too much effort instead of:

```js
const schema = {
  type: 'object',
  properties: {
    booleanConditionProp: {
      type: 'boolean',
      'x-display': 'switch',
      title: `I'm a boolean used to toggle the content below`
    },
    stringProp1: {
      type: 'string',
      title: `I'm a string available if the boolean switch is true`,
      'x-if': { booleanConditionProp: { const: true } }
    },
    stringProp2: {
      type: 'string',
      title: `I'm another string available if the boolean switch is false`,
      'x-if': { booleanConditionProp: { const: false } }
    },
    numberCondition: {
      type: 'integer',
      minimum: 0,
      maximum: 120,
      title: `I'm a number whose value is used to toggle content below`
    },
    stringProp3: {
      type: 'string',
      title: `I'm a string available if the number condition is less than 18`,
      'x-if': { numberCondition: { minimum: 0, maximum: 18 } }
    }
  }
}
```

Wdyt?

**Comment by albanm** [comment]
I agree that the syntax is lighter, at least it looks like it while you have single properties depending on your booleans. Still, one is JSON schema and will be applied both by vjsf and a validator like ajv, while the other is not.

What if you mix some validation rules, like making stringProp2 required ? Ajv will not consider that the property should not be evaluated, it will try and produce an error. A valid vjsf form will have produced an invalid json output from the point of view of json schema, which is one of the thing I try to prevent as much a possible. In my mind the standard workflow is a shared contract, vjsf client-side, ajv server-side and every validated form producing a valid input for the backend.

**Comment by sobrinho** [comment]
Oh, I see! I didn't check that the if/then/else was in the JSON spec, in that case, makes more sense to follow it. Thanks! ❤️
