### ISSUE TITLE
json-ref-lite error

### ISSUE THREAD

**Issue by PythonLinks** [koumoul-dev/vuetify-jsonschema-form#176]
json-ref-lite error: object ‘logoURL’ contains reference as well as other properties..ignoring properties

Here is the critical piece of JSON Schema. 

 "logoURL": {
          "title": "URL of thier photo.",
          "$ref": "#/definitions/url"
        } 

My Json Schemas have lots of URLS.  So I try to share the basic definition of a url, and only add a title to each one.  It looks like it does not like that. 
This guy was perfectly happy with that approach.

**Comment by PythonLinks** [comment]
https://github.com/json-editor/json-editor

Here is my URL definition. 
  "url":{ 
          "type": "string",
          "format": "uri",
           "pattern": "(^$)|(^(https?|wss?|ftp)://)",
           "description": "Please include \"https://\""
       },

When I switched my Logo definition to 
    "logoURL": {
          "title": "URL of thier photo.",
          "type": "string",
          "format": "uri",
           "pattern": "(^$)|(^(https?|wss?|ftp)://)",
           "description": "Please include \"https://\""
        } 

The sofware did not complain.  But now I am complaining.  I would like to update my url in one place, when I get a new regexp, rather than all over the place. 

Okay, the business I came here for is done.  Now to be a bit social. Hello everyone.  Thank you so much for this software.  I am busing working on Green Party Maps.  Map.Howie2020.tech.  You can watch some videos about it here. 
Map.Howie2020.tech/videos.

I model the whole US green party as a hierarchy, so JSON schema is perfect.  And politicians are quite complex, I have a massive JSON Schema.   

Your software is realy much more beautiful than the JSON Editor.  Plus your technology foundation is better.  That matters.  In particular it appears that you roll validation errors up the tree to the tabs across the top.  They do not do that correctly.  I have to do a jury rig to fix the problem.  Not good.  

When I get all of this working I want to start offering free online JSON schema classes.  A quick google search shows no good classes.  And JSON makes it so easy for javascript developers to configure complex models of people.    And it is a bit lonely socially isolating here in Poland, so it will be great to meet with a bunch of geeks once a week for a class. 
  
So wish me luck   And thank you for this beautiful library.

**Comment by albanm** [comment]
Hello,

Regarding json refs, the idea is that I included a small lib to handle some simple cases. But I don't really consider it to be part of the scope of this library. Whenever things become more complex I recommend to use other tools in some pre-processing step before passing the schema to vjsf.

Thanks for the feedback, and best of luck in your projects ! I agree that JSON schema deserves some promotion and quality content for beginners.
