### ISSUE TITLE
Missing v-chip-group type

### ISSUE THREAD

**Issue by speedyankur** [koumoul-dev/vuetify-jsonschema-form#178]
![Screenshot 2020-11-26 at 16 14 48](https://user-images.githubusercontent.com/1248020/100367472-49ce1600-3028-11eb-8b6e-330643cf82ab.png)

**Comment by speedyankur** [comment]
I would like to contribute in adding this in data type, this is something very special to Vuetify and which is not mostly available VJSF.

Please allow me to develop this one

**Comment by albanm** [comment]
I am sorry, this issue escaped my memory, I totally forgot to answer earlier.

If after all this time you are still interested in deloping this functionality, please tell me and ask me the questions you need.

**Comment by albanm** [comment]
This is covered by https://github.com/koumoul-dev/vuetify-jsonschema-form/pull/218 that should be merged soon.
