### ISSUE TITLE
Select with HTTP when parameter is empty

### ISSUE THREAD

**Issue by lalithakulkarni** [koumoul-dev/vuetify-jsonschema-form#179]
I have an address lookup API for which I am using the select with HTTP. The integration with this API works fine, with the select options populated. The problem that I am running into is the HTTP request is going through even if there is no query parameter in it, something like below

http://localhost:8080/address-lookup?query=

Preferably, the request only should go through if there was something that the user has typed in the input, like:

http://localhost:8080/address-lookup?query=960

Tried to use the nuxt axios helpers and see if I can use the canceltoken approach, but all the examples that I saw had cancel token passed along into the axios request. In the case of VJSF, since the request submission is automatically done, I can't see a way to pass cancel token.

Any help is highly appreciated.

**Comment by lalithakulkarni** [comment]
Looks like, I am able to get the desired result with the following Nuxt AXIOS helper

`import {
  CancelToken
} from 'axios'
export default function ({
  $axios
}) {
  $axios.onRequest((request) => {
    if (request.url.endsWith("/address-lookup?query=")) {
      const source = CancelToken.source();
      request.cancelToken = source.token
      source.cancel("Cancelling request")
    }
  })
}
`

Minor issue that I see is that it logs an error to the console from selectProperty.js. As this cancellation is intentional, the error being logged and dispatched from @koumoul/vjsf/lib/mixins/SelectProperty.js?cc00 is slightly misleading. 

I can live with it but want to see if there is a misunderstanding on my part or if there is a better way to do this. 

Appreciate your help.

**Comment by albanm** [comment]
I don't see a better way to do this in the current state of the lib, you should go with this solution for now.

I must take the time to think of a better way.

**Comment by lalithakulkarni** [comment]
Thank you @albanm for the great framework. I haven't hit a case that doesn't work so far. Great job.
