### ISSUE TITLE
Allow custom "component" component

### ISSUE THREAD

**Issue by scheepers** [koumoul-dev/vuetify-jsonschema-form#183]
Sometimes a custom component is needed to capture a piece of text, a phone number for example.

Is it possible to define a <component type="*" /> ?

It *looks* like it's possible to do so in /lib/mixins/SimpleProperty.js, but not sure if this would break the JSONSchema spec.

**Comment by albanm** [comment]
This is supported using slots, see [this example in the doc](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#slots).

**Comment by scheepers** [comment]
Oh, thank you. I misunderstood that whole thing.
