### ISSUE TITLE
x-rules function is not passed in correctly

### ISSUE THREAD

**Issue by kcsoft** [koumoul-dev/vuetify-jsonschema-form#188]
Adding x-rules only works for string (as a property of options.rules).
When adding a function, it fails with "Rules should return a string or boolean, received 'undefined' instead".

https://codepen.io/kcsoft/pen/gOwdPbJ

**Comment by albanm** [comment]
Sorry about that, but I have decided to remove this from the doc instead of fixing it. Schema is JSON, it has to serializable / deserializable and should not contain functions.
