### ISSUE TITLE
Validating fields in slots

### ISSUE THREAD

**Issue by joshhoegen** [koumoul-dev/vuetify-jsonschema-form#189]
Hi there!

What an excellent lib! There's only one more hurdle to jump before the team adopts it. 

When using a slot with an input for a field, I can't seem to get the validator to recognize the updated model. Though the validator works on another field that's generated by the lib. I don't expect the field in the slot to output an error, but I would expect the validator to check the model based on the schema specifications so that `valid === false`.

Here's a reproduction: https://codepen.io/joshhoegen/pen/jOMddvr

Despite being required and only accepting alpha chars, `v-model="valid"` isn't updated based off of the model...

- Is this the intended design? 
- Is there a recommended way I can ensure the form's v-model returns false?

Thanks for the lib and all the insight you share!

**Comment by albanm** [comment]
Hello,

Thanks for the feedback !

The library does not ensure strict schema validity in the sense that it does not use a schema validator internally (except optionally for the recent conditional schema functionality). It tries to map schema rules to validation rules in the underlying vuetify components. Basically validation rules are descending from the lib to the component, but validation status is bubbling from the component to the lib then to the parent form.

The slot context has a rules element that contains the validation rules that the property should implement. But bubbling the validation upward is not easy, as it requires implementing something similar to the [validatable mixin from vuetify](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/mixins/validatable/index.ts).

This is too complex for third party components included in slots, I need to rethink this. The lib should evaluate the rules and add validation status and error message in the slot context to be displayed by the component, then bubble the validation status by itself.

I will work on it, but I can't tell you when exactly.

**Comment by joshhoegen** [comment]
Ah! thanks for the info, @albanm. I imagine it wouldn't be cake walk. Feel free to send me the right files to look at and I may be able to work on a branch and open a PR.

**Comment by albanm** [comment]
Ok, I totally forgot that I had already thought of this scenario.

If you look at [this example](http://localhost:3000/examples#slots-wrappers) you will see that the 2 properties defined in slots are required and that when emptied they are properly shown as in error. If you look [here](https://github.com/koumoul-dev/vuetify-jsonschema-form/blob/master/doc/components/wrappers/v-jsf-toast-ui-editor.vue) you will see that this is achieved by wrapping the third-party component in a v-input. V-input will respect for you the conventions required by vjsf and vuetify for validation to work.

Let me know if this works for you of if your use case cannot be solved like that.

**Comment by albanm** [comment]
Otherwise you have the right starting points. The solution would be something like that:
  - in validatable.js, process the error messages by running this.rules and filtering those that return a string, probably move the computed property rules in the same mixin for clarity
  - add the error messages to the slot params
  - add a showValidation param in the slot params that would probably be (this.validated || this.shouldValidate)
  - in computed property hasError manage 2 cases:
    - either there are children inputs then keep the current implementation
    - or check the length of error messages
  - in the slot params in on.change set this.shouldValidate to true

I think that would do the trick while maintaining compatibility with the rest of the code. But I also think that using v-input is more in line with the framework.

**Comment by joshhoegen** [comment]
Cool! I see that in the first example, it works in an array. Couldn't quite figure out how to with the plain string field, however I'm enamored with the "input" use case! <3
