### ISSUE TITLE
Adding support to paste multiple values in v-combobox ( arrays with free input)

### ISSUE THREAD

**Issue by shirulaf** [koumoul-dev/vuetify-jsonschema-form#190]
Hi,

First thanks for your great library! Really a lifesaver.

Will it be possible to support pasting multiple values to an editable array, and to use delimiter props for separating the values?

So pasting: "a,b,c" will reslove with an array of:  [a,b,c,]

[like in this example](https://codepen.io/morphatic/pen/rXqzNg)

Thank you!

**Comment by albanm** [comment]
If I understand the example you simply want to add the delimiters prop to the combobox component.

If so you should be able to use something like that:

```json
"x-options": {"comboboxProps": {"delimiters": [","," "]}}
```

**Comment by shirulaf** [comment]
Thank you for your quick response.
The delimiter props work only by entering values one by one manually:
So if I have a delimiter of comma, I can manually press: "a" + "," +"b" => ["a", "b"], but in case I want to copy and paste multiply values, the delimiter has no effect, and pasting "a,b" will resolve with => ["a,b"]

[In the example I provided](https://github.com/koumoul-dev/vuetify-jsonschema-form/issues/190#issue-789134387-permalink:~:text=like%20in%20this%20example), there is a usage of @change event to handle this case.
As this library handles JSON schemas and forms, using multiple values, and the use case of pasting values, I believe is very handy to users.

**Comment by albanm** [comment]
Ok, I understand. But don't you think that this should be done in vuetify instead of vjsf, dit you try submitting an issue over there ? It feels like this should be the default functionality of the delimiters option.

**Comment by shirulaf** [comment]
Sounds right, thank you!

**Comment by albanm** [comment]
Closing for now, re-open if you wish to discuss this further.
