### ISSUE TITLE
v-model doesn´t update propertly

### ISSUE THREAD

**Issue by selobu** [koumoul-dev/vuetify-jsonschema-form#202]
I'm trying to make a buffer to store the data when some field in the form has changed, but for some reason the watch method is not capturing those events.

[codepen](https://codepen.io/Selobu/pen/bGBqgQK)

**Comment by albanm** [comment]
For now the model is mutated, not replaced (this might [change in the future](https://github.com/koumoul-dev/vuetify-jsonschema-form/issues/200#issuecomment-777026192)). Therefore you should use a watcher with the *deep* option.

**Comment by selobu** [comment]
Thank's a lot
