### ISSUE TITLE
How to disable tabs of sections

### ISSUE THREAD

**Issue by mahabubhossain** [koumoul-dev/vuetify-jsonschema-form#203]
I'm showing my sections as tabs. It's working properly. I've also implemented custom next &  previous buttons to move next & previous tab which are also working .

Now i want to disable click on tabs. Is there any option to do it??

i have seen vuetify [v-tab](https://vuetifyjs.com/en/api/v-tab/#props) has disabled prop but it's not working with VJSF

**Comment by albanm** [comment]
I think this was only meant as a way to simulate a proper stepper functionality.
