### ISSUE TITLE
Advice For Python Developers New to Node and VJSF.  And a question.

### ISSUE THREAD

**Issue by PythonLinks** [koumoul-dev/vuetify-jsonschema-form#207]
I tried installing the Debian version of Node, but that is out of date.    Similarly trying to download the newest version did not work.   The best thing you can do is use the Node version Manger. 
https://github.com/nvm-sh/nvm
It basically installs as a shell script.   No need to install as root.  Stores files in ~/.nvm.   And runs on startup by sourcing a shell script. 
Make sure nvm is working. 
>command -v nvm

Then tell it to install the latest version of Node
>nvm install --lts

Then you can do the recommended
>npm install
>npm run doc-dev

If you want to use an Ace editor, WYSIWYG HTML editor, or a markdown editor, the example is in doc/editor.vue. The problem is that there is no link to that page from the documentation.  Here is the documentation page. 
Node.GreenMaps.US

Here is the editor page
Node.GeenMaps.US/editor

Bit it does not actually do anything.  In particular I am not able to test the three editor content types.  But it does include the key Javscript one needs to use those three content types.  But I am not sure if they work, since I was not able to get the editor to work to  test them. 

In general Vue is a gradual framework.  One can add the libraries with a script tag, and start using Vue.  This beautiful VJSF framework is more complicated.  It makes heavy use of Node.js to package things.  Meaning that there is no distribution directory for the javascript needed to create the editors.  One actually has to fire up the application using Node, generate the distributions javascript, and include those javascript libraries in your application.   We Python developers would prefer a dist directory.  Even if that means that we are loading more Javascript than is absolutely necessary.  

Hopefully I got this all right.   Partially I write for others.  Partially to ask for guidance.  What do I have to do to get the editor working?

**Comment by albanm** [comment]
I think there is a misunderstanding.

The page doc/editor.vue is internal, mostly I used it to create the short video in the doc homepage. Ace is only integrated in this page to edit the schema, it is not integrated inside vjsf.

[This example](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#slots-wrappers). Describes how to integrate a third party component inside vjsf (tiptap and toast-ui editor used as first cases). A wrapper for ace can be written in a similar manner to extend the capabilities of vjsf, but it is not provided yet.
