### ISSUE TITLE
Separate v-input button from editable array

### ISSUE THREAD

**Issue by conmurphy** [koumoul-dev/vuetify-jsonschema-form#208]
I'm new to Vue and VJSF. I'm trying to find if there's a way to separate the button from the forms that I'm creating. This is for the "Editable array" which has the Plus button and "I'm an array of objects". At the moment the button is at the top of the page and I'd like to move it to the first column and have the second column hold the forms. 

Is this configurable or is there a workaround to accomplish it?

**Comment by albanm** [comment]
I don't really understand the expected result. The layout is not entirely customizable but there are a number of things that can be done (adding classes, using some slots, writing css rules, etc.).
