### ISSUE TITLE
Improved Starting Point

### ISSUE THREAD

**Issue by PythonLinks** [koumoul-dev/vuetify-jsonschema-form#210]
When I first visited this repository I noted  that both this package and he other nested json-schema Vue package use Bootstrap 3, and not Bootstrap 4.  That was a bit off-putting. At first I thought it was not up to date.  Now I suspect that Bootstrap 4 is too complex and not compatible with Vue.  Either way a statement in the docs would be useful.   Maybe I just have not found it yet. 

And why did I miss the playground?  Actually it was one of the first things I saw.  What I missed is the drop down menu.  I hyper focussed on the json, could not get it to do what I want and moved on. 

In contrast here is the playground for json-editor/json-editor. 

https://pmk65.github.io/jedemov2/dist/demo.html
Lots of big buttons hard to miss. 
Maybe you have more content types than they do.  They also do not bubble errors up to the tabs correctly.

**Comment by albanm** [comment]
I think this is not posted on the right repo. This lib uses vuetify (implementation of material-ui), not bootstrap.
