### ISSUE TITLE
Customizing icons

### ISSUE THREAD

**Issue by selobu** [koumoul-dev/vuetify-jsonschema-form#215]
Good afternoon

I would like to know if there is a way to set a custom prepend icon control , i.e. date control, info, datetime in cases where vuetify doesn't use  the mdi set icons by default.

Because I'm using my own icons set when configuring vuetify

`const opts = {
  lang: {
    locales: { es },
    current: "es"
  },
  icons: {
    values: { ...values }
  },
  theme: { dark: false }
};
export default new Vuetify(opts);`

![image](https://user-images.githubusercontent.com/11469144/110850810-3add3d80-827e-11eb-96ad-44b91fec8367.png)

**Comment by selobu** [comment]
yo can test it in this [codepen](https://codepen.io/Selobu/pen/BaQvMrw)

**Comment by albanm** [comment]
Yes, you can use the [icons option](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/configuration) to configure custom icons.

**Comment by selobu** [comment]
I posted a request to fix the bug

**Comment by albanm** [comment]
I don't understand. You posted a request where and about what bug ? The option does not work ?

**Comment by selobu** [comment]
Good afternoon

By default library vjsf should read the icons that are defined in vuetify, for my case I made a global configuration on vuejtify where I defined my own icons and I expected vfjs to use them but it was not the case.
With the suggested changes the mentioned problem is solved.

**Comment by selobu** [comment]
possible  to commit the changes you should check if passing options to vsjf is working, I really dont't do it.

**Comment by albanm** [comment]
What changes are you talking about ? I don't see a pull-request.

What you expect is vjsf icons option to be replaced by the content of vuetify icons.values instead of only using icons.iconfont as it does now ?

**Comment by albanm** [comment]
Ok, sorry if I am slow to understand. I thought you had already pushed some changes somewhere but I understand now that you were simply making a suggestion.

I am ok with reading vuetify icons.values in vjsf. If you can push a commit I will have a look, otherwise I will do it myself soon.

**Comment by selobu** [comment]
I'm sorry, please check the pull request.
