### ISSUE TITLE
Upgrade to Vuetify 2.x

### ISSUE THREAD

**Issue by bam-tbf** [koumoul-dev/vuetify-jsonschema-form#22]
Upgrade to use Vuetify 2.x

I have begun the work of switching to vue-cli and using vuetify 2.x components. It is mostly working, but there is some more debugging to do. I can make a pull request when it is ready for review if that would be appreciated.

**Comment by kleinjm** [comment]
Unfortunately this package is not useful to my project until it's on 2.x. Thanks

**Comment by albanm** [comment]
I juste published a version with vuetify 2 support.

As there were not many breaking changes, I managed to keep support for vuetify 1 in the same code base (jusrt dealing with a few edge cases, adding older classes, etc.).

The [demo](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/) uses vuetify 2.

An [alternative demo](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/vuetify1.html) uses vuetify 1.

I hope I didn't miss any breakage.
