### ISSUE TITLE
Changing model via code not working when using sections

### ISSUE THREAD

**Issue by rFranzr** [koumoul-dev/vuetify-jsonschema-form#220]
When using (tabbed) sections, changing the form model in the code, does not affect the contents of the input fields.

Example: https://codepen.io/rFranzr/pen/LYbqzrE?editors=101

Am I missing something or is this a bug?

**Comment by albanm** [comment]
Well this is kind of a bug. Ideally reactivity should work perfectly in both directions, but this is quite difficult to achieve and maintain. For the time being you should not presume that it works in all cases and instead trigger a redraw of vjsf in case of a model (or schema) change from outside.

**Comment by rFranzr** [comment]
Thanks for the fast reply.
Since it is working with a non sectioned form I thougt it is also working with a sectioned one.

What exactly do you mean with redraw the form and how do I achieve this?

**Comment by albanm** [comment]
This [article](https://michaelnthiessen.com/force-re-render/) is good on the subject.
