### ISSUE TITLE
Question: [SOLVED] How to remove the set default background for Text-Area?

### ISSUE THREAD

**Issue by Mashiane** [koumoul-dev/vuetify-jsonschema-form#226]
Hi there

How do I make the text-area background the same as the rest of the element. I only set the auto-grow, rounded, outlined here, it seems it has a set default background color.

<img width="417" alt="textarea" src="https://user-images.githubusercontent.com/5799306/114076535-0ec9d200-98a7-11eb-8ccb-1a8d37d1529a.png">

**Comment by albanm** [comment]
I don't think vjsf does anything specific here, it just uses vuetify. Either you can solve it using vuetify props or you can write some css to override the color.

**Comment by Mashiane** [comment]
Thanks, will check and see what I can apply. Its rather strange because on the Vuetify docs, the background color when the filled property is set, it works like that. I have not set that property on my case, but just auto-grow.

**Comment by Mashiane** [comment]
Solved, have set the background-color x-prop to transparent.

**Comment by albanm** [comment]
Ah yes, I forgot. See [here](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/configuration), the default for textareaProps is {filled: true}, you can overwrite the props with filled=false to cancel this.

**Comment by Mashiane** [comment]
Great then, thanks, I didn't notice that.
