### ISSUE TITLE
Question: For date element, how to remove the prepend icon & turn clearable off?

### ISSUE THREAD

**Issue by Mashiane** [koumoul-dev/vuetify-jsonschema-form#227]
Hi there

For the date, how can I remove the prepend icon & also turn off the clearable? Thanks

<img width="393" alt="DateX" src="https://user-images.githubusercontent.com/5799306/114077439-19d13200-98a8-11eb-8f0a-03b8d786c980.png">

**Comment by albanm** [comment]
Clearable is removed if the field is required, maybe you can use that. The prepend icon cannot be removed for now.

**Comment by Mashiane** [comment]
Thanks, please consider adding these and rather make them user-dependent and not pre-set conditions.

Just a thought. The required you are talking about, can it be set on / off? I am thinking of a conditional way of turning required on / off for some elements depending on some conditions.

**Comment by albanm** [comment]
Actually it is possiblle to remove the prepend icon, with options={ icons: { calendar: null, clock: null } }
