### ISSUE TITLE
Question: [SOLVED] How to apply v-show so that you can hide an element

### ISSUE THREAD

**Issue by Mashiane** [koumoul-dev/vuetify-jsonschema-form#228]
Hi there

I'd like to hide the ID element on my dialog, i have applied it via x-props, v-show=idhide and set idhide model to false, it does not seem to work. I assigned a model.

<img width="405" alt="hideelement" src="https://user-images.githubusercontent.com/5799306/114078033-be537400-98a8-11eb-825d-1ffaa39ce2f3.png">

**Comment by albanm** [comment]
v-show is not a prop but a directive, it does not work. Please look at the example about read-only content https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#read-only You can use x-display=hidden for example.

**Comment by Mashiane** [comment]
Thanks x-display=hidden works perfectly. Please consider adding the v-if and v-show directive.
