### ISSUE TITLE
wrong behavior with required fields of non-required nested objects

### ISSUE THREAD

**Issue by MOHACGCG** [koumoul-dev/vuetify-jsonschema-form#230]
**Issue:** A model should be valid with an undefined optional nested obj with required fields (i.,e `{stringProp:"a"}` is a valid model for the schema below).

**Feature request:** Is it possible to remove an optional nested object from the model? in the schema below remove the nestedObj (i.e. set it to undefined). The array type already allows removal of items, so this is to support the same behavior to remove objects.

```
{
  "type": "object",
  "properties": {
    "required":["stringProp"]
    "stringProp": {
      "type": "string",
      "title": "I\"m a string",
      "description": "This description is used as a help message."
    },
    "nestedObj": {
      "type": "object",
      "properties": {
        "num": {
          "type": "number"
        },
        "str": {
          "type": "string"
        }
      },
      "required": ["num", "str"]
    }
  }
}

```

**Comment by albanm** [comment]
I am aware of this problem and I need to think about it. Initializing an empty object is built kinda deep in the way the lib works (necessary to bind the children properties on it). But the implementation of model binding and reactivity has changed quite a lot in 1.25 beta, maybe it has become easier to fix.

**Comment by MOHACGCG** [comment]
I have schema workaround for now (use a toggle switch) to turn the object on and off but would be nice to have this built in.

```
"allOf": [
        {
          "allOf": [
            {
              "properties": {
                "!__ nestedObj_toggle": {
                  "title": "NestedObj,
                  "type": "boolean",
                  "x-display": "switch",
                  "default": false
                }
              },
              "if": { "properties": { "!__ nestedObj_toggle": { "const": true } } },
              "then": {
                "properties": {
                  "verify": { "$ref": "#/$defs/nestedObj" }
                }
              },
              "else": {}
            }
          ]
        },
...]
```

**Comment by saveliy-sviridov** [comment]
Hello,
It appears that this issue still persists as of the current version;
@albanm would you happen to have an idea on how to approach it, or whether it even seems theoretically possible at all to resolve without rewriting the whole lib to you? I'm sadly not in a position to modify the schema so I'm trying to find another solution.
