### ISSUE TITLE
Question: Displaying Rating, Progress Linear, Progress Circular, Images?

### ISSUE THREAD

**Issue by Mashiane** [koumoul-dev/vuetify-jsonschema-form#236]
Hi

How can I define and display a rating, a progress linear, progress circular, an image?

Thanks for your help.

**Comment by albanm** [comment]
When something is not cover by the llibrary you have to implement it using slots. See these 2 examples: https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#slots

**Comment by Mashiane** [comment]
Ok thank you, I will try. I just didnt want to start something that could be upcoming in your next version as I saw the beta indicator.

Please if you dont me, dont be impatient, Im just starting this out and exploring vue and the lot of questions I ask might set you off.

Thanks.

**Comment by albanm** [comment]
No problem you can keep asking, just don't expect fast answers every time, it depends on my free time and my mood :)

Please think of closing the issues once you are satisfied with a response.
