### ISSUE TITLE
Render descriptions of custom field implementations like default fields

### ISSUE THREAD

**Issue by scheepers** [koumoul-dev/vuetify-jsonschema-form#237]
I implement a few custom widgets for fields and it works beautifully, thank you.

Is it possible to render descriptions like the information popups as the default fields do?

I've looked ate the demo fields but their descriptions render differently to the defaults. 

It would be great for consistency on form displays

**Comment by albanm** [comment]
Yes, that is something that needs improvement. For now you can have a look [here](https://github.com/koumoul-dev/vuetify-jsonschema-form/blob/master/lib/mixins/Tooltip.js#L14) and maybe recreate the same functionality inside your widgets.
