### ISSUE TITLE
Items not rendered in an array with items under anyOf

### ISSUE THREAD

**Issue by yaffol** [koumoul-dev/vuetify-jsonschema-form#241]
Hello, thank you for this library, it's great.

I am loading a schema [(pen)](https://codepen.io/yaffol/pen/yLgRaVm) which has an array defined, at the location `journal.issns` the possible items for which are nested under an `anyOf`.

When I load this schema into the form, nothing is rendered for that array. I can see a `<Vjsf key="issns"/>` component in Vue dev tools, but nothing shows up on screen.

I wondered if it was caused by a missing `type` property under the `journal.issns.items` key, so I tried adding one. 

Setting `type: "object"` causes the ISSNs label and  + button to show up, when you click it, a blank dialog box appears, and there's an ajv error in the console `"Error: schema is invalid: data.properties should be object"` 

Setting `type: "string"` causes the ISSNs label to appear, and an input area, where you can enter strings (which are validated).
However, you can't select which sort of ISSN you are adding (no subSchema selection).

Here's [a pen](https://codepen.io/yaffol/pen/mdRzraG) that shows that.

I'm not sure if I can modify the schema to work better to, or if I've hit an edge case.

I've tried the same schema in [JSON Editor](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIBBKbAw6ABABMqEMIhji2UQRF0p2XHgotEY8W3CQaQMzAYXikqIgCtHUIAEQB5AEkTOPhsQRMAJXCqMPgMXXtHZ1duOxAyMzNfBDkABSlIHNgaVCI5RCo2CAanQxgWtBB4hMiiwkQoKW8AcwUIMigoHPhCAD0ARgAGAB1tgDpds2AAFhYATgBfAHoAbQBaPd4AbgAKAEorlD07gC1Nu7Oq12iAAugBqEAXC5sMIARxEMDCZlQNyGiRAIOhIBESEmIh4IiRoXCkVs0RcAFVcVJ8VBCVQzCYwkQclQ8gUQA4nIQwJxSgoKlVYDVsPVGn0Bm1sB0uj0mv1kINmaz2aNuS4JlN4LMoTCqPDEQyUSBlbl8hisZrafSzMSIoMosUAMp4glIpnZM0crnFXluMqC6rwOpyiWKqUykDdcXNRWgDiiKTB7C8R1q4qamaQthkMTKaTp8aTLNYrxSCa8ebTZyaMYueAiOh4HLZkCCKhkKSFjXF7VzBZLJNrG7rAEgm7/M7jyfTscAEkhWLhCKRxoThOTqbJHNzUHzXbY7c7Fq6ZGrvEQ8xWDu3hFqZ6oJkvZBWhXVJXcOcqQZDMYVrXaToo1DWMAjLCsqxrTlbxcAAxREJhMSCFB9CRG2bLssQECCH1JbRigAGTIRDkLfYoGybFtdRNfUVyNFBUXAvhSJAbDmNwzEcz6YwqF4CiMLw8kQAMIxTH4lsyJ5PlP3Kb9hWTMVelAlAIyA6MlP/QZxK7G98MIAA5dCJM5OsQG0xc9QNVcGLMoyu048BUm8XiYEQRBr00GCQCoBInSdfSPBoDApmgPxCF8/yTBIKQTBwZyTAANxyGwEBQ0zMz7U9FmWQgbl2J0QROC5djuPLtgKorW26bw+Fc9zBOKCKArYCwlBC+Twr8/SoukJCtSgRLkrCySey1WYssHa8QDKirjmK7ZSvywq5tbOr4AvUowt0oSmuQFqgvarbHNweBHxfRlqvgAbdrS99OykIQFDobwEiWOhFXWNhZAAD1etRFQAJjYWx/oCF9BDie0bk8vSXB8rrAramBQtSlwmp6mK4tOwby2Gkz3wy8aowHHKXBm5b5sW8qKezGGdoR/akZRqb0eivqapxlLX3xjNeyJ+ZsqHMmlqKkrycqi5MSwzBeHhOQYC8ZKGsIW7fWkgM5L8X8NMlQDZT/AZQAmTs+DMBYoLTFwXRN8xzcR4LkY6lwABVVFtpYTAWEwKGUTBlBMPdH1wfIkEfcgAGsaBMcIWR4EwXhERARDkNIA7dxAyAYT3EDTx8IBEPBg4WPx3aoN5VaLMaFGi2RxBcM2llbDgyAS5WXAAKT0AA1Tm8dQ0aszYNlG2NPQMHyaAGRMABZF9E4d6AFC7oaEFiohMm4aRkRBfa2hEbA65AZfcdXsB16yLApGRajl0NZEbONwxeAbjlm9bhzx/4TA2Q6NuQAAYTCMXJKJh/70DoKvAi39Q4VxcH6fkX4hRa1FCBTSql9Y6zjCAT+hJ5DbWKIAjssAQFgLoBApAJhg4/0fLg+2h1UYgFdo+CkGQCJr1zqAoBxDHykPITnKhMCRqKD5goYedBjTKEWBARAKArhXGCkQmASUsBkIQIgPY0hphXAER0RAVw8CCCuMcPYmwrgKEkVAaRsj5FcKUZvVRSANFSC0Tomg+jBB3AzkYkxZi2AWKsXIhRwD7F8KcS46Buj3F3HgGYbxpjzFSJkYE2xyjwFqLCdoiJbiDHRIwHE3xIB/FJJsYo1JDj1GaMySHSJOS8ieLIPkhJljilBO4So0JlTXF6NqRgaJsTjHxJ3oEcIycD6ECKdY1pdj2npM6Vk7phiBlmKxHLXAityx/1gR+DWSCRSKXlLraUalUGG2ESbZ+dt8GEGtoYUudDHZHSYaXT2A0fZ+w4a4gOZBI45xjqUeOidRmp0Dk+TOZ0c4gvzoXTAxdV4v3LkIwm1dpC10IC/JuLc/6dx7klE+3N+7CKrkPCio9x6WCWIyWeDYmZlGPlzdhF8t4Yl3rmMZLg6UlzPhvS+18ly0TvsaR+ps7ZsDfhaPlVl6KohwVIeQDkwCBykF/apFsvJxEVSYKBKqtnwJkoGeS2sDnhj1sBA2WCFWqCVbQq5LgtXUJMLQxmC8nbCRMCwthe4vZWBqhCsAnsTBYAgIIKY0xJFPnIG9NkA1eqDneiYAAZAGhAuz/CIpEWwGuCxCCEhgIFPebLCmJOsVQb6mcIA6D2Coqp1DWyrIVv0DZNqQA6vVgKTWeyTnGqORgo1AQhUXMbk2m5A10VOvoVNJ5L8Xne19ioD5WSvk/OjkQWOA0E5JxTukEFGcs7EQ4VCou8lS4Ip5pXQexAUVZvrnbLEYqm3Yt7qlNNRLvIkpsmPCeFKZ5zxpUvFe8AGWbyvsy4Z+bD4ctPufIDvLLJ0Xvqifto6QBiqlrBgVNkLU5F4LQhyri7R/ztaHEw3hM0dTHQ8hhhGOjEfgKRkubM9DTxYCYLucQMhbPuo9L6L03qKk2F9Mgv1eOoC2MDYTgxwaQxRHTAhKSeFpIA1R70pldU7J/Cgs1AFu2mswQEGVeCZOEEIcE0BCn+ELsdcMmljy3buvYSC4z3DTPlMoVkrZSLiUjxshM5JpSQmzOcdW0OCzGl+KLb54JMzHFzJVQs+poXC3NMmXJqLFTAtdKiTEhLPmSmRbMxkjLPTsvhdy20/LMXqFxbqV4pZTSAmlemeV9L8zMu9Ky7VoZnhRmHxy1MspHTmuxfcY0lZoz61KybS2/0baU2GrDFpyM6le2DEQ5cwzVtyC3KQ61Z1NnHxTq9m8udILPkRyjn8uO66gVbvTmC7O+6C6HpLvC9z6aL0yCvYEG9orMX3u7o+/F6U3tiNJZ+qeVL57tT/XiwDPKQOeFZeB/9sOmU335dZBDm3hWNx++/NHkr4PYIwNh2VJ51sgHVZazVbmhGqZm+p/Z82VImqW0z0AmGrWk6bUph1pPyPM30G61hacvXBCur6/1gbg0wFDQNY2karqxRirGnOiasAxKDHtU9A9MrvdRS4HNebEfjJKyWstFaq2uNrWN9ZWDLbNtp62xBDPO0LeOZplbWOB2qthiAYddz+cusnebadR3/YnYXWd35K7/lXc3Rwnd4KHvQowLCgDL3n3ntI2i77yHfvk4fbirmr2X0g/fWSyelKf3Ouh/SrljLgOdfCMb9lyP6/QYsjRAngqvdIZQ/juDxoOck7lZLKEWJWfKVACrUViZkxYrn3IEwCRaOXrI9r7ZcxXeDCIPvFMlsC+L+wAHW8mfddm7oOWgYqJ25H/YbURAggVBgHyA9Z6GBkAOTIHgPAYQEpblhnJz0B/z/xgHNkZHXCTCXzTDPyJgvyv0VBvziFqH/hPBAASjAGwEbB9yEi7kwOwK2XMixDqhEBwMajclIMILsiqkexhXkm9z/lqFoNTyPSQwJQ8z10+3RWILcn8CbRukDyOixjOhiXZkVwEI3040ECeh41BhQE+hAB+j+nelQCBhABBhUIk3gAhihnJ3hn8nuQFzRi6gxliicmxiLz7iBxfQFkmlyhFjmjFgcIuFpmgl9yakMJdVZl6kugGksKfQ3w4NsNJmmmcKcOpglilnH0tHzAoF4ByAaEbXUKuhyDIB4D7lUAYEIDwDAAVU1DIAgGOAUFviJAMWfmb33jrnQUCFcnLSEGJAJ14BwGkOZ200QFiKaOgF4G8DdzYEkF4H1WQUrG32qLIGbm+l6JqIzkLl4gZFsF4A4FoGvDxCAiqGmJ0F4CwGwAEGkWcBWJalcm/w2Mn00n2KmKON4ikIGMqEmLWIuIGKkAekEGJC3hbFaMjDuJmIeKePKJ0EHWqLZHuKuKl0mOBNIAaGlFTEgFQDOM+I2KuIsD+MuO2NCDAAoC7Q+MOK+IRKoCRP4GIj4AaAoDdyhCAA) and it seems to work, which makes me think the schema is probably OK.

I'd be very interested in working on an PR to fix or extend the library to support this, if it is an edge case.

**Comment by yaffol** [comment]
Update: I was able to [make it work](https://codepen.io/yaffol/pen/mdRzraG) by copying more directly from the subSchema example in the docs, but the previous schema does definitely work in JSON-editor and React JSON Schema Form which makes me think it would be possible to enable it within Vuetify JSON Schema Form.

Any pointers gratefully received.

**Comment by yaffol** [comment]
Closing as there is a workaround.

**Comment by albanm** [comment]
Sorry for the lack of response. Good to hear that you found a workaround, I will try to have a look at your example later today or in the next few days.

**Comment by yaffol** [comment]
Ah thanks for the reply - I didn't want to leave a complex but workaround-able issue hanging around, but it would be good to get to the bottom of it.

I'm evaluating a load of JSON Schema form libraries for my employer, and I am very interested in this one (we have standardised on Vue/Vuetify as our UI framework) but one of the big things preventing me from adopting it immediately is the lack of ordering in the form.

So fields defined in the schema being ordered differently in the UI, depending on whether they are strings/objects as in https://github.com/koumoul-dev/vuetify-jsonschema-form/issues/187.

I would be interested in fixing this at source - I noticed this doesn't happen with the other libraries I'm looking at ([React JSON Schema Form](https://github.com/rjsf-team/react-jsonschema-form), [Vue JSON Schema Form](https://github.com/crickford/vue-json-schema-form) and my baseline which is [JSON Editor](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIBBKbAw6ABABMqEMIhji2UQRF0p2XHgotEY8W3CQaQMzAYXikqIgCtHUIAEQB5AEkTOPhsQRMAJXCqMPgMXXtHZ1duOxAyMzNfBDkABSlIHNgaVCI5RCo2CAanQxgWtBB4hMiiwkQoKW8AcwUIMigoHPhCAD0ARgAGAB1tgDpds2AAFhYATgBfAHoAbQBaPd4AbgAKAEorlD07gC1Nu7Oq12iAAugBqEAXC5sMIARxEMDCZlQNyGiRAIOhIBESEmIh4IiRoXCkVs0RcAFVcVJ8VBCVQzCYwkQclQ8gUQA4nIQwJxSgoKlVYDVsPVGn0Bm1sB0uj0mv1kINmaz2aNuS4JlN4LMoTCqPDEQyUSBlbl8hisZrafSzMSIoMosUAMp4glIpnZM0crnFXluMqC6rwOpyiWKqUykDdcXNRWgDiiKTB7C8R1q4qamaQthkMTKaTp8aTLNYrxSCa8ebTZyaMYueAiOh4HLZkCCKhkKSFjXF7VzBZLJNrG7rAEgm7/M7jyfTscAEkhWLhCKRxoThOTqbJHNzUHzXbY7c7Fq6ZGrvEQ8xWDu3hFqZ6oJkvZBWhXVJXcOcqQZDMYVrXaToo1DWMAjLCsqxrTlbxcAAxREJhMSCFB9CRG2bLssQECCH1JbRigAGTIRDkLfYoGybFtdRNfUVyNFBUXAvhSJAbDmNwzEcz6YwqF4CiMLw8kQAMIxTH4lsyJ5PlP3Kb9hWTMVelAlAIyA6MlP/QZxK7G98MIAA5dCJM5OsQG0xc9QNVcGLMoyu048BUm8XiYEQRBr00GCQCoBInSdfSPBoDApmgPxCF8/yTBIKQTBwZyTAANxyGwEBQ0zMz7U9FmWQgbl2J0QROC5djuPLtgKorW26bw+Fc9zBOKCKArYCwlBC+Twr8/SoukJCtSgRLkrCySey1WYssHa8QDKirjmK7ZSvywq5tbOr4AvUowt0oSmuQFqgvarbHNweBHxfRlqvgAbdrS99OykIQFDobwEiWOhFXWNhZAAD1etRFQAJjYWx/oCF9BDie0bk8vSXB8rrAramBQtSlwmp6mK4tOwby2Gkz3wy8aowHHKXBm5b5sW8qKezGGdoR/akZRqb0eivqapxlLX3xjNeyJ+ZsqHMmlqKkrycqi5MSwzBeHhOQYC8ZKGsIW7fWkgM5L8X8NMlQDZT/AZQAmTs+DMBYoLTFwXRN8xzcR4LkY6lwABVVFtpYTAWEwKGUTBlBMPdH1wfIkEfcgAGsaBMcIWR4EwXhERARDkNIA7dxAyAYT3EDTx8IBEPBg4WPx3aoN5VaLMaFGi2RxBcM2llbDgyAS5WXAAKT0AA1Tm8dQ0aszYNlG2NPQMHyaAGRMABZF9E4d6AFC7oaEFiohMm4aRkRBfa2hEbA65AZfcdXsB16yLApGRajl0NZEbONwxeAbjlm9bhzx/4TA2Q6NuQAAYTCMXJKJh/70DoKvAi39Q4VxcH6fkX4hRa1FCBTSql9Y6zjCAT+hJ5DbWKIAjssAQFgLoBApAJhg4/0fLg+2h1UYgFdo+CkGQCJr1zqAoBxDHykPITnKhMCRqKD5goYedBjTKEWBARAKArhXGCkQmASUsBkIQIgPY0hphXAER0RAVw8CCCuMcPYmwrgKEkVAaRsj5FcKUZvVRSANFSC0Tomg+jBB3AzkYkxZi2AWKsXIhRwD7F8KcS46Buj3F3HgGYbxpjzFSJkYE2xyjwFqLCdoiJbiDHRIwHE3xIB/FJJsYo1JDj1GaMySHSJOS8ieLIPkhJljilBO4So0JlTXF6NqRgaJsTjHxJ3oEcIycD6ECKdY1pdj2npM6Vk7phiBlmKxHLXAityx/1gR+DWSCRSKXlLraUalUGG2ESbZ+dt8GEGtoYUudDHZHSYaXT2A0fZ+w4a4gOZBI45xjqUeOidRmp0Dk+TOZ0c4gvzoXTAxdV4v3LkIwm1dpC10IC/JuLc/6dx7klE+3N+7CKrkPCio9x6WCWIyWeDYmZlGPlzdhF8t4Yl3rmMZLg6UlzPhvS+18ly0TvsaR+ps7ZsDfhaPlVl6KohwVIeQDkwCBykF/apFsvJxEVSYKBKqtnwJkoGeS2sDnhj1sBA2WCFWqCVbQq5LgtXUJMLQxmC8nbCRMCwthe4vZWBqhCsAnsTBYAgIIKY0xJFPnIG9NkA1eqDneiYAAZAGhAuz/CIpEWwGuCxCCEhgIFPebLCmJOsVQb6mcIA6D2Coqp1DWyrIVv0DZNqQA6vVgKTWeyTnGqORgo1AQhUXMbk2m5A10VOvoVNJ5L8Xne19ioD5WSvk/OjkQWOA0E5JxTukEFGcs7EQ4VCou8lS4Ip5pXQexAUVZvrnbLEYqm3Yt7qlNNRLvIkpsmPCeFKZ5zxpUvFe8AGWbyvsy4Z+bD4ctPufIDvLLJ0Xvqifto6QBiqlrBgVNkLU5F4LQhyri7R/ztaHEw3hM0dTHQ8hhhGOjEfgKRkubM9DTxYCYLucQMhbPuo9L6L03qKk2F9Mgv1eOoC2MDYTgxwaQxRHTAhKSeFpIA1R70pldU7J/Cgs1AFu2mswQEGVeCZOEEIcE0BCn+ELsdcMmljy3buvYSC4z3DTPlMoVkrZSLiUjxshM5JpSQmzOcdW0OCzGl+KLb54JMzHFzJVQs+poXC3NMmXJqLFTAtdKiTEhLPmSmRbMxkjLPTsvhdy20/LMXqFxbqV4pZTSAmlemeV9L8zMu9Ky7VoZnhRmHxy1MspHTmuxfcY0lZoz61KybS2/0baU2GrDFpyM6le2DEQ5cwzVtyC3KQ61Z1NnHxTq9m8udILPkRyjn8uO66gVbvTmC7O+6C6HpLvC9z6aL0yCvYEG9orMX3u7o+/F6U3tiNJZ+qeVL57tT/XiwDPKQOeFZeB/9sOmU335dZBDm3hWNx++/NHkr4PYIwNh2VJ51sgHVZazVbmhGqZm+p/Z82VImqW0z0AmGrWk6bUph1pPyPM30G61hacvXBCur6/1gbg0wFDQNY2karqxRirGnOiasAxKDHtU9A9MrvdRS4HNebEfjJKyWstFaq2uNrWN9ZWDLbNtp62xBDPO0LeOZplbWOB2qthiAYddz+cusnebadR3/YnYXWd35K7/lXc3Rwnd4KHvQowLCgDL3n3ntI2i77yHfvk4fbirmr2X0g/fWSyelKf3Ouh/SrljLgOdfCMb9lyP6/QYsjRAngqvdIZQ/juDxoOck7lZLKEWJWfKVACrUViZkxYrn3IEwCRaOXrI9r7ZcxXeDCIPvFMlsC+L+wAHW8mfddm7oOWgYqJ25H/YbURAggVBgHyA9Z6GBkAOTIHgPAYQEpblhnJz0B/z/xgHNkZHXCTCXzTDPyJgvyv0VBvziFqH/hPBAASjAGwEbB9yEi7kwOwK2XMixDqhEBwMajclIMILsiqkexhXkm9z/lqFoNTyPSQwJQ8z10+3RWILcn8CbRukDyOixjOhiXZkVwEI3040ECeh41BhQE+hAB+j+nelQCBhABBhUIk3gAhihnJ3hn8nuQFzRi6gxliicmxiLz7iBxfQFkmlyhFjmjFgcIuFpmgl9yakMJdVZl6kugGksKfQ3w4NsNJmmmcKcOpglilnH0tHzAoF4ByAaEbXUKuhyDIB4D7lUAYEIDwDAAVU1DIAgGOAUFviJAMWfmb33jrnQUCFcnLSEGJAJ14BwGkOZ200QFiKaOgF4G8DdzYEkF4H1WQUrG32qLIGbm+l6JqIzkLl4gZFsF4A4FoGvDxCAiqGmJ0F4CwGwAEGkWcBWJalcm/w2Mn00n2KmKON4ikIGMqEmLWIuIGKkAekEGJC3hbFaMjDuJmIeKePKJ0EHWqLZHuKuKl0mOBNIAaGlFTEgFQDOM+I2KuIsD+MuO2NCDAAoC7Q+MOK+IRKoCRP4GIj4AaAoDdyhCAA). I wondered if you had any insight as to why it's different in Vjsf, and where to start looking to fix it? Of all the libraries, this is by far and away the best looking and nicest to use as a form user, so if I can help to fix it up, I'd be glad to.

**Comment by albanm** [comment]
I chose to display simple children on top and section children (objects with titles and allOfs) at the bottom for these reasons:

  - sections and simple props are not always naturally ordered together (coming from properties or coming from a allOf)
  - sections are not always visually mixable with simple properties (tabs, expansion panels)
  - even when they could be mixed it makes for a poorly readable form (section with a title, then a simple prop that kinda looks like it is part of the previous section just a little bit more to the left, then another section)

But I am willing to consider improvements to offer more power to the user. I just don't want things to become too complicated (there already are enough head-scratching pieces of codes in this lib). The most relevant part of the code is [here](https://github.com/koumoul-dev/vuetify-jsonschema-form/blob/master/lib/mixins/ObjectContainer.js#L320).

One thing to understand with vjsf is that I deliberately chose not to separate structure and presentation. In my opinion it makes for something more manageable, but it comes with important limitations.
