### ISSUE TITLE
Integration with Nuxt ?!

### ISSUE THREAD

**Issue by linqFR** [koumoul-dev/vuetify-jsonschema-form#242]
Hello, 

I need a piece of advice: What is the better way to integrate vjsf into nuxt for Single Page Application (and i18n and tailwindcss) ?

That is:
- buildModule or module?
- build : transpile? or else ?

and while in dev mode, that could be cool to get something like localhost:3000/vjsf or /forms to develop forms and save them to components 😉 (as it exist for tailwind) !

Thanks !

**Comment by VictorioBerra** [comment]
I would also like information on how to import and use this as a Nuxt plugin.

**Comment by IOIIOOIO** [comment]
I found some clues here:

https://github.com/koumoul-dev/vuetify-jsonschema-form/issues/305
