### ISSUE TITLE
Question: Is there a way to limit which properties are displayed in an object array

### ISSUE THREAD

**Issue by satra** [koumoul-dev/vuetify-jsonschema-form#245]
currently we have a set of objects that have a number of properties and nested objects. when the list is created this makes it really difficult to navigate. the example below shows a partial object in an array of about 30 objects.

would it be possible to show only a subset of properties so that one can navigate an array quicker and the full set of properties is shown only when one goes into edit mode? in the example below, i would simply like to show the name property of the object for all objects. (this would also make it easier to move the order of objects)

![image](https://user-images.githubusercontent.com/184063/115790835-5b2c0c00-a395-11eb-9d8f-ef9b854d54d1.png)

**Comment by albanm** [comment]
Totally forgot about this issue sorry. I agree that I need to think of an easy way to configure different rendering between readonly item displayed in the array and full editable item.
