### ISSUE TITLE
Support for mdi icons

### ISSUE THREAD

**Issue by nicolas-bonnel** [koumoul-dev/vuetify-jsonschema-form#25]
Vuetify 2.0 now uses mdi icon set. We need an option to configure this library to use another icon set. Date pickers use the `event` icon code which is the one of material icons, for mdi it is `calendar`

**Comment by wysman** [comment]
Same issue here.
An easy solution will be to overwrite icons name in the option parameter.

**Comment by ngrie** [comment]
Hey @albanm , great to see this got just implemented. I would love to start using mdi icons, will you push this change to npm anytime soon?

**Comment by albanm** [comment]
Done, available in 0.29.0.
