### ISSUE TITLE
Latest stable version?

### ISSUE THREAD

**Issue by mbilbille** [koumoul-dev/vuetify-jsonschema-form#251]
Hello,

Which is the latest stable version?
If I refer to the repository homepage it is the [1.16](https://github.com/koumoul-dev/vuetify-jsonschema-form/releases/tag/v1.16.0)
If I refer to the tag naming it is the [1.24.1](https://github.com/koumoul-dev/vuetify-jsonschema-form/releases/tag/v1.24.1)

Thanks in advance for your help.

**Comment by albanm** [comment]
I don't aways think of creating a release on github for each version i push on npm. But anything pushed on npm without a beta flag should be considered as usable. Basically whatever comes when running `npm install @koumoul/vjsf`.
