### ISSUE TITLE
Stepper styles

### ISSUE THREAD

**Issue by johngtb** [koumoul-dev/vuetify-jsonschema-form#259]
![Screenshot from 2021-06-14 22 05 08](https://user-images.githubusercontent.com/6325182/121952613-c58d7700-cd5c-11eb-9e66-1bd72994c15d.png)
I'm trying to get a flat stepper (no elevation) with full width.
tried the following but no luck:
`"x-props": { "flat": true }`
`"x-props": { "outlined": true }`
and
`"x-style": "width: 100%;"`

**Comment by albanm** [comment]
Did you try the stepperProps / verticalStepperProps options ?

**Comment by johngtb** [comment]
For stepper props, it tuned out I was using an older version of Vuetify that doesn't support many props including "flat".

However, I found 2 fixes to Vjsf vertical stepper:

1. full width style (copied from horizontal stepper)
2. code typo in `verticalStepperProps`

Please merge https://github.com/koumoul-dev/vuetify-jsonschema-form/pull/260

**Comment by albanm** [comment]
thanks, merged and released in v2.0.3
