### ISSUE TITLE
Question: use v-model modifiers in textfields

### ISSUE THREAD

**Issue by weissphi** [koumoul-dev/vuetify-jsonschema-form#262]
hi,

Is there a possibility to set v-model modifiers for components. 
I want to trim the input into a generated text field. For this I would like to use a v-model.trim, but I don't see a way to pass this in the options.

thank you

**Comment by albanm** [comment]
Not possible for now, you will need to apply the modification yourself. But that would be a nice addition to the current functionalities, I will think about it.

**Comment by ftonato** [comment]
Hi @albanm, is there any plan to release this?

**Comment by albanm** [comment]
I don't think v-model modifiers can be used in render functions (not templates). I think it would have to be implemented entirely by vjsf, something like a set of standard and custom modifiers referenced by schema properties.

No immediate plan. But I don't close the issue either, it is interesting for the roadmap.

**Comment by ftonato** [comment]
I don't know if it fits the tool's proposal, but maybe we could pass a property called `shouldTrim` or something and if it was present, it would remove the `.trim() spaces. when the input received the value.

**Comment by albanm** [comment]
If think I would aim for something a little more generic similar to vuejs modifiers. Something like `x-modifiers=["trim", "uppercase"]`.
