### ISSUE TITLE
Just a curious question

### ISSUE THREAD

**Issue by Mashiane** [koumoul-dev/vuetify-jsonschema-form#266]
Is it possible to use this library to "hook" to existing element (those that were not created using the lib), and then change them depending on your options.

`<v-btn id="xxx">Me</v-btn>`

For example, assuming that a  already existing on your page, then by some miracle

You want to "hook" vjsf to that, e.g. xy = vjsf.get("xxx") then you run a method on some returned vjsf object and change an attribute/style at runtime at run-time?

Does what im saying make sense perhaps / understandable?

**Comment by albanm** [comment]
I don't think I entirely understand the question, but maybe this can be of help:

The closest thing would probably be to include a custom component using a slot https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#slots-wrappers

This custom component is integrated as a slot, but it is also possible to make it run some code that interacts with other parts of the page.
