### ISSUE TITLE
How can I know which field was changed in logEvent function

### ISSUE THREAD

**Issue by Vision70** [koumoul-dev/vuetify-jsonschema-form#280]
Hello,

How can I know which field was changed in logEvent function?

In the exemples, there are only 2 parameters passed to the function logEvent. The 'key' and $event, that is the model.

When I receive the $event parameter, it's the model updated. But I don't know which field was changed.

Is it possible to identify this?

Thank you.

Marcelo

**Comment by albanm** [comment]
On top of input and change events that relay only the root model, you get input-child and change-child that contain some context. The new events might create some quite messy output and need some tuning, but the idea is there.
