### ISSUE TITLE
Reset Model doesn't work

### ISSUE THREAD

**Issue by ValDewez** [koumoul-dev/vuetify-jsonschema-form#295]
Hi,

I am currently working on a project and I am not able to reset my form. The model is set to {} but the data is still visible while in Vue inspector there is no data in the component.
I tried multiple way to clear like 
`for (var prop in obj) { if (obj.hasOwnProperty(prop)) { delete obj[prop]; } }`

I also tried to simply reset my like this:  model = {};

Here is a screenshot of my current data not resetting while VueJS inspector doesn't have any data from model.

![image](https://user-images.githubusercontent.com/62611076/131978671-218f1f59-af44-4945-ba2d-35b336b4f56a.png)

Here is a screenshot from console.log I did before and after my reset

![image](https://user-images.githubusercontent.com/62611076/131978998-db2d6201-e5cd-4982-b117-f48369c36275.png)

And Here is a capture with VueJs value from vjsf at blank but my data still on my screen

![image](https://user-images.githubusercontent.com/62611076/131979093-188fc90e-840f-4e7a-a3b7-6442fdde3827.png)

Edit: There is only 1 field on my screen with the data not appearing, others still not reset.

Thanks for the help,

Valentin

**Comment by albanm** [comment]
please have a look at https://github.com/koumoul-dev/vuetify-jsonschema-form/issues/58

**Comment by ValDewez** [comment]
Thanks a lot, I'll take a look.
