### ISSUE TITLE
How to refer to the data in the context through another form item?

### ISSUE THREAD

**Issue by cheezone** [koumoul-dev/vuetify-jsonschema-form#297]
```
context={
brands:[ {
                                title: 'Xiaomi',
                                value: 'Xiaomi',
                                brands: ['Xiaomi', 'Redmi', 'BS', 'POCO'],
                            },
                            {
                                title: 'Huawei',
                                value: 'Huawei',
                                brands: ['Huawei', 'Honor'],
                            },]
}
```
...
```
designedBy: {
                                    title: 'designedBy',
                                    type: 'string',
                                    'x-fromData': 'context.brands',
                                    'x-itemTitle': 'title',
                                    'x-itemKey': 'value',
                                },
                                dependencies: {
                                    designedBy: {
                                        brand: {
                                            type: 'string',
                                            title: 'brand',
                                            'x-fromData':
                                                'context.brands[designedBy].brands',
                                        },
                                    },
                                },
```
When select "Xiaomi", Should show ['Xiaomi', 'Redmi', 'BS', 'POCO'].
But it doesn't work

**Comment by albanm** [comment]
For now this is not supported, the expression in x-fromData is a simple getter not a complete expression. I am working on using dynamically created JS functions to handle more complete expressions that could combine data from the context and the model, it should be available in 1 or 2 days. But this functionality will be activated using an option with a strong warning, to use it you will have to have complete trust in the source of the json schema (not a problem in most cases as the source of the schema is the same as the code source of the application itself, but not always the case).

**Comment by cheezone** [comment]
Thank!

**Comment by albanm** [comment]
please have a look [here](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#select-context-deps) and [here](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/configuration#expressions)

**Comment by cheezone** [comment]
Okay, I will go to see it, thank you for your work!
