### ISSUE TITLE
How to change the value of the form by listening to input events?

### ISSUE THREAD

**Issue by cheezone** [koumoul-dev/vuetify-jsonschema-form#298]
I listened to the `input-child` event and changed the `v-model` value of the form. When the change was made, the output value was correct, but it did not take effect in the form display. When the next event was triggered, the change I just made in the output form value disappeared.  

Is it related to this?

> better implementation of v-model by not mutating the value parameter and instead creating clones for each input event (better for clarity and side-effects)
> https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/1to2

How can I keep this change in the form display by change the Object directly?

When I change this `<input>` value and use `dispatchEvent` , it work but too troublesome......

**Comment by albanm** [comment]
Unfortunately this is not supported by vjsf, once bound the model is only reactive one way. See https://github.com/koumoul-dev/vuetify-jsonschema-form/issues/58

**Comment by cheezone** [comment]
Thanks!
