### ISSUE TITLE
Sections as Expansion Panels: I want to expand only some sections/panels by default

### ISSUE THREAD

**Issue by xfavalon** [koumoul-dev/vuetify-jsonschema-form#300]
Hi,

**Problem:** I want to control which panels are expended initially. 

Without Vjsf, I have to add v-model directive to the v-expansion-panels component and set an array filled with the indexes of the panels that I want to be expanded. See the image. 

Is it possible to achieve this feature using VJsf? 

if is not, is it possible to add vue directives when rendering a component in the Vjsf code? 

Thanks!

![image](https://user-images.githubusercontent.com/90746804/134534018-eb5bb15a-f4f2-4209-88b5-ea49128640b8.png)

**Comment by albanm** [comment]
Yes, you can give all necessary props to the v-expansion-panels instance, see https://codepen.io/albanm/pen/qBjMawJ?editors=101

**Comment by xfavalon** [comment]
Thanks!
