### ISSUE TITLE
custom code slots are ignored if the form is displayed on v-dialog

### ISSUE THREAD

**Issue by johngtb** [koumoul-dev/vuetify-jsonschema-form#302]
Hi Alban, I have some code slots with a "custom-" prefix and passed to the "x-display" annotation in my schemas which work perfectly everywhere in my app except when the form is placed on a "v-dialog" or "v-sheet" in which case the custom elements are totally ignored and a normal input is displayed instead along with the rest of the schema inputs.

**Comment by albanm** [comment]
Hi,

Can you try to recreate your problem in a codepen ? It is easy to initialize a codepen from the examples in the documentation.

**Comment by johngtb** [comment]
it turned out that I'm using another instance of the schema form on that dialog that was missing the definitions of my custom inputs. Sorry for opening this and thanks for your fast reply.
