### ISSUE TITLE
Can i mask fields?

### ISSUE THREAD

**Issue by GiovannyLucas** [koumoul-dev/vuetify-jsonschema-form#31]
-

**Comment by GiovannyLucas** [comment]
Hello, I was wondering if there is any way to mask the fields...

**Comment by albanm** [comment]
Hello,

Yes, you can add "x-display": "hidden" to a property.

**Comment by GiovannyLucas** [comment]
Can you show me an example?

**Comment by albanm** [comment]
https://github.com/koumoul-dev/vuetify-jsonschema-form/blob/master/demo/examples/basic.js#L47

**Comment by GiovannyLucas** [comment]
![photo_2019-09-13_16-39-06](https://user-images.githubusercontent.com/41789184/64890067-1da5bf80-d645-11e9-8db4-078d958dfbc7.jpg)

I wanted to leave it that way

**Comment by albanm** [comment]
Oh ok ! No this is not supported.

**Comment by GiovannyLucas** [comment]
Do you have any forecasts to add?

**Comment by albanm** [comment]
I hesitate to add ever more dependencies and options to this library.

For this use case maybe you could use the recent (and not very well documented) slot functionality ?

cf https://github.com/koumoul-dev/vuetify-jsonschema-form/blob/master/demo/DemoApp.vue#L63 for an example.

**Comment by ribrewguy** [comment]
Any update on this feature?

**Comment by GiovannyLucas** [comment]
I think it's still unavailable. You can find this feature in this [library](https://github.com/wotamann/vuetify-form-base#schema). I hope it helps.

**Comment by albanm** [comment]
Available through the use of a directive, see https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#directives
