### ISSUE TITLE
integer slider reporting value

### ISSUE THREAD

**Issue by gunstonej** [koumoul-dev/vuetify-jsonschema-form#314]
hi there, 

great tool! 

is it possible to show the selected value on the integer slider? 

[basic types](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#basic)
![image](https://user-images.githubusercontent.com/21370980/141443687-b5ddcfb3-9fdd-4852-b275-23eec0bc9803.png)

I'm developing for scientific applications where knowledge of the numeric value is required. 

Many Thanks

**Comment by albanm** [comment]
Hi,

Just use the thumbLabel prop from v-slider, for example `"x-props": {"thumbLabel": "always"},`

**Comment by gunstonej** [comment]
perfect - thanks!
