### ISSUE TITLE
support for numeric ranges

### ISSUE THREAD

**Issue by jgunstone** [koumoul-dev/vuetify-jsonschema-form#321]
does vjsf support numeric ranges?

e.g. 
![image](https://user-images.githubusercontent.com/21370980/143405456-597ddffe-fce6-48d2-99d9-a943ca4b3d6d.png)

I had a read through the docs but couldn't find anything. 

cheers

**Comment by albanm** [comment]
?o, that would have to be a custom component in a slot for the time being.

But I might look into it at some point, or accept a pull request if someone wants to work on it.
