### ISSUE TITLE
[x-if] expression 

### ISSUE THREAD

**Issue by Meplos** [koumoul-dev/vuetify-jsonschema-form#322]
Hey! How to use newFunction expression in an x-if.

**Comment by theRenard** [comment]
How ?

**Comment by albanm** [comment]
It is quite hidden in the doc but [this example](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#select-context-deps) uses newFunction.

Please note that a new function is compiled, but the provided string is not a full function signature, only an expression that will injected after a return statement, see the [source code here](https://github.com/koumoul-dev/vuetify-jsonschema-form/blob/master/lib/VJsfNoDeps.js#L352).

**Comment by albanm** [comment]
I think it didn't feel natural to inject multiple line statements, function definitions, etc. A simple string in a JSON file is not the good place to write large chunks of dynamic code. But you should be able to call more complex functions either from the global scope or referenced in options.context.
