### ISSUE TITLE
Image selection / enum 

### ISSUE THREAD

**Issue by JuliusJacobitz** [koumoul-dev/vuetify-jsonschema-form#323]
Hi @albanm, 
I am trying to build an image selector based on urls. My goal is to select one url from an array of urls, but to display the images instead of the url. I came across a solution that works with v-select. Is there a way to accomplish this in vjsf? Or could you think of another solution? I tried to fiddle with slots etc. but couldn't get it to work.

[Link to v-select solution](https://stackoverflow.com/questions/61775457/vuetify-v-select-with-image)

![t](https://i.stack.imgur.com/ACjmF.png)

**Comment by albanm** [comment]
Did you see this example https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#select-icons ?

**Comment by JuliusJacobitz** [comment]
Thank you for your quick answers! And yes I did, currently using it. Is there a more customizable way?

**Comment by albanm** [comment]
For more customization you would need to use a custom component I think, see https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#slots-wrappers.
