### ISSUE TITLE
Listening for change

### ISSUE THREAD

**Issue by uaru** [koumoul-dev/vuetify-jsonschema-form#326]
<v-jsf v-model="model" :schema="schema" @change="doSomething">

Suppose there are a few text elements inside. If the user type something, for the event @change to take place, he needs to change focus from the field. So I cannot detect if the user just started typing until he starts something else.

@input - a lot of events even before I start typing anything, so it is useless.
@keyup - does not work.

Did I miss something?

**Comment by albanm** [comment]
Maybe input-child is better for your use-case ? https://github.com/koumoul-dev/vuetify-jsonschema-form/blob/master/lib/VJsfNoDeps.js#L397
