### ISSUE TITLE
The possibility of adding custom content

### ISSUE THREAD

**Issue by euller88** [koumoul-dev/vuetify-jsonschema-form#33]
The tool is good enough, but it lacks some features like, text masking, custom validation rules, file handling(apparently), and custom fields. I'm not a JS expert, but I can imagine that this could be achieved by two methods: first, creating new properties every a time a functionality is needed; second, devise a mean to developers inject their own components to cover for some functionality that is not ready out of the box. I'm more tempted to say that the second method is more viable, due to the usage of slots, because it can add flexibility to the component and give more time to add new functionalities that follow the identity of the package.

**Comment by albanm** [comment]
Yes, allowing users to inject custom components using slots is one of the things I want to add. But not a priority right now. Of course pull requests are welcome as usual.

**Comment by albanm** [comment]
Ok, I changed my mind. I wanted to check the feasibility and ended up implementing a simple slots mechanism. I think it is usable. I added a "Slots" [demo](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/) and the code of the slots is [here](https://github.com/koumoul-dev/vuetify-jsonschema-form/blob/master/demo/DemoApp.vue#L58).
