### ISSUE TITLE
Computed field

### ISSUE THREAD

**Issue by selobu** [koumoul-dev/vuetify-jsonschema-form#348]
it's posible to define computed fields?

**Comment by albanm** [comment]
I am not sure I understand. Do you mean that you want to extend the schema dynamically ? vjsf does not guarantee that it will react property to any kind of dynamic change to the schema. In this case it is best to recreate the component instance.

**Comment by selobu** [comment]
Some forms could define computed fields based on another input  on the same form.
The computed fields should be readonly and have to evaluate expressions in a secure way by using a parser as peggy <https://peggyjs.org/online.html>, also I guess the computed field should evaluate simple tokens like COMA, IF, SUM, MINUS, and so on.

**Comment by albanm** [comment]
I don't know if this belongs to the scope of vjsf or if it should be done
in the wrapping vue code. It feels a little bit like reinventing the
wheel. Maybe having a readonly field in the form, and a computed property
in vue whose setter writes into the model. Or using a slot.

**Comment by semanticarlo** [comment]
Hi, I am interested in computed fields as well.
Immagine a form with 2 fields: 
- name (user edits this)
- IRI (cannot be edited by user)

Can the JSON-schema specify that ID should be equal to "http://my/domain/" + name ?
