### ISSUE TITLE
Customise item / selection slots

### ISSUE THREAD

**Issue by theRenard** [koumoul-dev/vuetify-jsonschema-form#353]
Hi, I'm unable to configure item and selection slots, as per documentation this "should" work but maybe I'm wrong

              template( slot="myField-item" )
                span item // this doesn't work

              template( slot="myField-selection" )
                span selection // this doesn't work

              template( slot="myField-append" )
                span append // this works

              template( slot="myField-before" )
                span prepend // this works

Any idea ?

**Comment by albanm** [comment]
Unfortunately this is a known limitation https://github.com/koumoul-dev/vuetify-jsonschema-form/issues/281

These slots are overwritten by vjsf.

**Comment by theRenard** [comment]
Ok thank you anyway, great library 👌
