### ISSUE TITLE
Using the selection slot in v-file-input in order to show the titles of the files

### ISSUE THREAD

**Issue by fonte85** [koumoul-dev/vuetify-jsonschema-form#360]
Hi,

I'm building my own v-file-input component similar to FileProperty.js in the mixins folder, and I want to use the selection slot feature (https://vuetifyjs.com/en/components/file-inputs/#slots) in order to show the titles of the selected files as you can see in the picture:

![image](https://user-images.githubusercontent.com/108865945/177753374-c58f70f7-c4ee-4fcc-aa4d-786a2d48201e.png)

To achieve this, I have to create a template tag into the v-file-input as you can see in the picture:

![image](https://user-images.githubusercontent.com/108865945/177771386-606951db-0845-47f6-ada3-e1ad39a817a6.png)

But I don't know how to reproduce the v-slot:selection directive in order to pass the text property using the render function h().  

Another approach is using the attribute slot="selection" and slot-scope="data" for the template tag but it doesn't work either.

What is the best approach?

Thanks

**Comment by albanm** [comment]
I think [this code](https://github.com/koumoul-dev/vuetify-jsonschema-form/blob/master/lib/mixins/ColorProperty.js#L15) looks very much like what you are trying to accomplish.

**Comment by fonte85** [comment]
Thanks Alban

This is how I solved it and it works well.

`h('v-file-input', { scopedSlots: { selection: ({ text }) => h('v-chip', { attrs: { color: 'primary' } } , text ) } } )`
