### ISSUE TITLE
Multiple types combined with pattern can break validation

### ISSUE THREAD

**Issue by jakobsa** [koumoul-dev/vuetify-jsonschema-form#369]
Given:
```
{
	type: 'object',
	properties: {
		anyProp: {
			"type": [
                              "string",
                              "boolean"
                          ],
                          "pattern": "^[^${}]+$",
                          "default": true
		}
	}
}
```

Expected result: 
> validation ok, and {anyProp: true}

Actual result: 
> TypeError: e.match is not a function

Analysis:
when applying validation rules, string is expected but other type (in this case: boolean) is given.

**Comment by albanm** [comment]
What does json-schema say about that ? Are you sure a validator like ajv will ever accept a boolean value, or will it always estimate that it fails the pattern rule ?

**Comment by jakobsa** [comment]
https://www.jsonschemavalidator.net/ is fine with it.

**Comment by albanm** [comment]
This sort of problem should be better in current version as validation is entirely delegated to ajv.
