### ISSUE TITLE
FYI: vuetify-jsonschema-form repl

### ISSUE THREAD

**Issue by cugu** [koumoul-dev/vuetify-jsonschema-form#373]
I needed an option to quickly test generate forms with vjsf so I built a vuetify-jsonschema-form live evaluation tool: https://cugu.github.io/vjsfrepl/

Feel free to close this "issue", just wanted to share this.

**Comment by albanm** [comment]
Thanks and sorry for the lack of response. I always hesitate to integrate a full editor in the doc or encourage people to use codepens.
