### ISSUE TITLE
overwrite the default localized messages

### ISSUE THREAD

**Issue by eti88** [koumoul-dev/vuetify-jsonschema-form#374]
Hello, as written [here](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/configuration#messages) I am struggling to overwrite the default localized messages. I tried to pass them as options.messages property into component but isn't working.

Can anyone provide a working example?

**Comment by dominikhorn93** [comment]
Hi @eti88 could you post your code here, hard to help with the little info
