### ISSUE TITLE
Populate Select using selected values of another Select

### ISSUE THREAD

**Issue by rmirro** [koumoul-dev/vuetify-jsonschema-form#375]
I have a `select` that I'd like to populate with selected (checkbox) items from another `select`.

I seem to have this partially working, although the dynamically populated `select` is displaying the item value as the title, but I'd like the title of the select item displayed.

[Here is a codepen to demonstrate how it's working now.](https://codepen.io/rmirro/pen/ZEobqEb)

**Is this type of functionality supported?**

---

I've tried defining the dynamic `select` as both a regular property and as a `dependency` below.

![Screen Shot 2022-09-07 at 12 21 14 PM](https://user-images.githubusercontent.com/79159738/188933758-4a191603-9bd6-47c3-bdcc-8da7620141c6.png)

---

Schema:

```
const schema = {
  type: 'object',
  description: 'Select As Dependency',
  'x-display': 'expansion-panels',
  'x-props': {
    mandatory: false,
  },
  'x-options': {
    hideReadOnly: true,
  },
  properties: {
    cards: {
      title: 'Cards',
      description: 'Select cards that should be enabled.',
      type: 'object',

      properties: {
        availableCards: {
          type: 'array',
          title: 'Available Cards',
          'x-display': 'checkbox',
          items: {
            type: 'string',
            oneOf: [
              {
                const: 'card-one',
                title: 'Card One',
              },
              {
                const: 'card-two',
                title: 'Card Two',
              },
              {
                const: 'card-three',
                title: 'Card Three',
              },
              {
                const: 'card-four',
                title: 'Card Four',
              },
            ],
          },
        },
        enabledCards: {
          type: 'array',
          title: 'Enabled Cards',
          items: {
            type: 'string',
          },
          'x-display': 'checkbox',
          'x-fromData': 'parent.value.availableCards',
          'x-itemTitle': 'title',
          'x-itemKey': 'const',
        },
      },
      dependencies: {
        availableCards: {
          properties: {
            enabledCardsDependency: {
              type: 'array',
              title: 'Enabled Cards Dependency',
              items: {
                type: 'string',
              },
              'x-display': 'checkbox',
              'x-fromData': 'parent.value.availableCards',
              'x-itemTitle': 'title',
              'x-itemKey': 'const',
            },
          },
        },
      },
    },
  },
};
```

**Comment by albanm** [comment]
I just released version 2.19.0. I added the schema to the context given to expressions, so this use case is now supported if you activate a more powerful expression mode (evalExpr of newFunction), see [this example](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#select-schema-deps) for more details.

**Comment by rmirro** [comment]
Wow, that looks perfect!

I really lucked out with the timing of this new release! 😄

**Comment by rmirro** [comment]
It seems like `2.19.0` provides exactly what I was hoping for.
