### ISSUE TITLE
widget to create geometry

### ISSUE THREAD

**Issue by pvgenuchten** [koumoul-dev/vuetify-jsonschema-form#378]
In our domain we often include a geometry as part of a data object (for example as part of [geojson](https://geojson.org)). it would be interesting to have a widget which allows to draw such a geometry.

Such a widget would consist of an interactive map viewer with draw functionality. A common library for maps is [leafletjs](https://leafletjs.com). Various drawing modules exist, for example this one: https://leaflet.github.io/Leaflet.Editable/example/index.html

Results of drawing could be stored as:
- simple: {"point": [0,0], "box": [[0,1],[2,3]] }
- or geojson: { "geometry": {  "type": "Point",    "coordinates": [125.6, 10.1]} }
- or wkt: { "wkt": "LINESTRING(1.5 2.45,3.21 4)" }

Is this of interest to the group?

**Comment by albanm** [comment]
Yes this is interesting. Is is one of the things that I intended to do someday or another. If someone else does it that's great !

Personally I did not use leaflet for a long time, I tend to use maplibre.

This might not necessarily be submitted as a pull request, instead it can be a wrapper component compatible to be included in vjsf in a slot.

**Comment by pvgenuchten** [comment]
I have not looked at maplibre much yet, but indeed is also an option

I’ll check the slot docs, good suggestion
