### ISSUE TITLE
update select binding issue

### ISSUE THREAD

**Issue by abumalekFayed** [koumoul-dev/vuetify-jsonschema-form#379]
I have form  include select with data source from context,the data source is array of object  and i set x-itemTittle and x-itemKey to bind with key
the problem appear when trying to update record and set the model with a specific key the select not work and no selection was happen.

**Comment by albanm** [comment]
Can you provide an example ? Maybe in the form of a codepen (you can use links in the doc to initialize a codepen).

**Comment by abumalekFayed** [comment]
https://codepen.io/gafbxjvt/pen/RwyyWOx
when try to edit item from the list binding to select id not work

**Comment by albanm** [comment]
I think this another case of https://github.com/koumoul-dev/vuetify-jsonschema-form/issues/58

Vjsf does not work well with model changes from outside, you have to re-render.

**Comment by abumalekFayed** [comment]
I think this is different from  #58 case, as in my situation the form is rendered partially the problem with select component only but in #58  the form is not rendered at all.
is there any solution, please?

**Comment by abumalekFayed** [comment]
Thank you the problem was solved by setting select type to a number instead of a string as binding id is a number
thank you very much for your awesome work.
