### ISSUE TITLE
Tooltip as link (sometimes)

### ISSUE THREAD

**Issue by Martin-Idel** [koumoul-dev/vuetify-jsonschema-form#383]
Sometimes, in larger forms, the "help" dialog requires more explanation than makes sense in a tooltip window - or information that changes often and should not be part of the forms. In that cases, there are often pages that I'd like to link to. 

Since in vjsf the information tooltip is opened on click anyways, it would be great if there was a possibility to make the tooltip so that if the description is link-only, it opens the link in a new tab instead. Obviously, such a behaviour could be hidden behind a property so that it works as before for everybody else.

Does that make sense to you? Would you accept a PR for that?

**Comment by albanm** [comment]
Yes sure, that makes sense.
