### ISSUE TITLE
Conditional X-cols prop to be 12 in mobile screen and 6 in widescreen

### ISSUE THREAD

**Issue by abumalekFayed** [koumoul-dev/vuetify-jsonschema-form#389]
How to implement Conditional x-cols prop to be 12 in mobile screen and 6 in widescreen.

**Comment by albanm** [comment]
x-cols can be an object with lg, xl, etc properties

**Comment by abumalekFayed** [comment]
You are awesome man special thanks.


في الثلاثاء، ٢٢ نوفمبر ٢٠٢٢, ١٠:٣٠ م Alban Mouton ***@***.***>
كتب:
