### ISSUE TITLE
Non-required fields become required after interaction with them

### ISSUE THREAD

**Issue by mvandenburgh** [koumoul-dev/vuetify-jsonschema-form#395]
Given the following (abbreviated) sub-schema for an array of `Person`s:
```
"Person": {
  "title": "Person",
  "type": "object",
  "properties": {
    "id": {
      "title": "ID",
      "description": "Uniform resource identifier",
      "readOnly": true,
      "type": "string"
    },
    "schemaKey": {
      "title": "Schema Key",
      "default": "Person",
      "type": "string",
      "const": "Person"
    },
    "name": {
      "title": "Name",
      "description": "Use the format: familyname, given names ...",
      "nskey": "schema",
      "examples": [
        "Lovelace, Augusta Ada",
        "Smith, John",
        "Chan, Kong-sang"
      ],
      "type": "string"
    },
    "email": {
      "title": "Email",
      "nskey": "schema",
      "type": "string",
      "format": "email"
    },
    "url": {
      "title": "URL",
      "nskey": "schema",
      "minLength": 1,
      "maxLength": 1000,
      "format": "uri",
      "type": "string"
    },
	...
  },
  "required": [
    "name",
    "schemaKey"
  ]
},
```

Note that the `url` field is not `required`. However, if the user starts typing something into the `url` field and then deletes it, vjsf will report the input as invalid due to the `minLength` being 1. I don't think this is the correct behavior; since `url` is not a `required` field, an empty `url` input should be valid.

MVCE: https://codepen.io/mvandenburgh/pen/WNjzGdw

GIF reproducing the bug:
![vjsf](https://user-images.githubusercontent.com/37340715/208504042-92cb71a1-14eb-4ac0-ae23-48d65623ac38.gif)

**Comment by bendichter** [comment]
I would also be interested in a fix for this. Thanks!

**Comment by albanm** [comment]
A fix similar to this one is probably required : https://github.com/koumoul-dev/vuetify-jsonschema-form/commit/effa0c25cf77371bd4b5a13c3e20ac5e77823d1a

**Comment by mvandenburgh** [comment]
Thanks for the tip @albanm! I'll look into implementing a fix like that.
