### ISSUE TITLE
use via JS file

### ISSUE THREAD

**Issue by vdvpie22** [koumoul-dev/vuetify-jsonschema-form#4]
How can I use Your component via JS file?
Like:
<script src="https://cdn.jsdelivr.net/npm/vue@2.5.22/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify-jsonschema-form.js"></script>
for example.

**Comment by albanm** [comment]
This is not battle tested as I personnally use npm and webpack to load from the lib folder, not the dist folder.

But these links should work:

https://cdn.jsdelivr.net/npm/@koumoul/vuetify-jsonschema-form@0.20.0/dist/main.js

https://cdn.jsdelivr.net/npm/@koumoul/vuetify-jsonschema-form@0.20.0/dist/main.css

**Comment by vdvpie22** [comment]
Thanks for the quick response.
I try to use main.js and I get an error about that unknown component.

`  <script src="https://cdn.jsdelivr.net/npm/vue@2.5.22/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.js"></script>
    <link rel="stylesheet" href="main.css">
    <script type="text/javascript" src="main.js"></script>
  </head>
  <body>
    <div id="app">
      <v-form v-model="formValid">
        <v-jsonschema-form v-if="schema" :schema="schema" :model="dataObject" :options="options" @error="showError" />
      </v-form>
    </div>
  </body>
.....

var vm = new Vue({ el: '#app',
    data: {
      schema: myScema,
      dataObject: {},
      formValid: false,
      options: {
        debug: false,
        disableAll: false,
        autoFoldObjects: true
      }
  },
    methods: {
      showError(err) {
        window.alert(err)
      }
    }
  });`

`vue.js:616 [Vue warn]: Unknown custom element: <v-jsonschema-form> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

**Comment by albanm** [comment]
do you have maybe a "VJsonschemaForm" global var ? That you could load using something like Vue.use(VJsonschemaForm) ?

**Comment by vdvpie22** [comment]
No, please look at the image, maybe it will be clearer what I am doing :))
![image](https://user-images.githubusercontent.com/8426935/52375070-d08abb00-2a6f-11e9-9d24-71b2fd281e9c.png)

**Comment by albanm** [comment]
Why simply use main.js and main.css and not the full urls ? Did you copy the js files in your folder ?

Did you check if the script was properly loaded without mistake ? Also did you check if a "VJsonschemaForm" global var was created using something like "console.log(window.VJsonschemaForm)". If it is present it should be usable as a Vue component, using something like Vue.use() or Vue.component(...).

**Comment by vdvpie22** [comment]
console.log(window.VJsonschemaForm) - exist

var vm = new Vue({ el: '#app',
    components: {
      VJsonschemaForm
    },
    data: {
      schema: myScema,
      dataObject: {},
      formValid: false,
      options: {
        debug: false,
        disableAll: false,
        autoFoldObjects: true
      }
  },
    methods: {
      showError(err) {
        window.alert(err)
      }
    }
  });
in this case, i see error:
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <VJsonschemaForm>
       <VForm>
         <Root>

**Comment by albanm** [comment]
Ok. I will try to test this myself in a short while.

**Comment by apb2006** [comment]
This works for me
```
  components: {
    "v-jsonschema-form": VJsonschemaForm.default
   },
```

**Comment by albanm** [comment]
The README now includes instructions to load through cdn or using vuetify "à la carte" mode.

**Comment by glikoz** [comment]
```
import VJsonschemaForm from '@koumoul/vuetify-jsonschema-form'
Vue.component('v-jsonschema-form', VJsonschemaForm) 
```

works for me!
