### ISSUE TITLE
Docs use deprecated slot-scope / slot properties

### ISSUE THREAD

**Issue by darioackermann** [koumoul-dev/vuetify-jsonschema-form#403]
`slot` and `slot-scope` are deprecated since Vue 2.6.0.
The docs however use them, e.g. https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#slots-wrappers

The alternative to use is e.g. `<template v-slot:custom-object1="context">`.
I can add a PR if you want me to?

**Comment by albanm** [comment]
Sure, a PR would be welcome.

**Comment by darioackermann** [comment]
PR is in https://github.com/koumoul-dev/vuetify-jsonschema-form/pull/404. 
Thanks for maintaining this awesome lib! 🥳
