### ISSUE TITLE
ArrayProp with schema dependencies

### ISSUE THREAD

**Issue by luana880910** [koumoul-dev/vuetify-jsonschema-form#415]
Hi there,

I was wondering if there's a way for users to classify the names of objects in an arrayProp into another arrayProp. 
Here's an example:

Suppose we have an old arrayProp with the following items: A, B, C, D, E, F, G. 
Is it possible to classify these items using an array of strings?

For instance, we could have a new arrayProp B, that contains the following items: A', B', C'.

A' item = {A, B}
B' item = {C, D, E}
C' item = {F, G}

If you could provide any guidance on how to achieve this, it would be greatly appreciated.

Thank you!

**Comment by albanm** [comment]
Hello,

Sorry but I don't fully understand your use case. Did you see the parts of the doc about using dependencies (https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#select-relative-deps) ? Maybe that fits into this category, maybe not.
