### ISSUE TITLE
Feat: AdditionalProperties

### ISSUE THREAD

**Issue by paveldelpozo** [koumoul-dev/vuetify-jsonschema-form#424]
Is there any plan to add the functionality that a schema contains `additionalProperties` and the form can dynamically add key/value field pairs similar to how the equivalent react library does?
![image](https://github.com/koumoul-dev/vuetify-jsonschema-form/assets/55382850/9bcce412-cafa-494f-bc3f-f84b4910f198)

See the example by clicking on "Additional Properties" button.
[React-JsonSchema-Form](https://rjsf-team.github.io/react-jsonschema-form/)

**Comment by albanm** [comment]
Yes, I would like to support this.

But I can't set a date unfortunately, planning is tight.

**Comment by paveldelpozo** [comment]
Thank you for your quick answer... I will be attentive to the news of each new version.
