### ISSUE TITLE
x-directives seems to be broken

### ISSUE THREAD

**Issue by Jared-Kim** [koumoul-dev/vuetify-jsonschema-form#426]
I have been trying to use x-directives to set a mask like the example seen here in the documentation https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples/#directives. However, I can't seem to get the mask to apply, and the codepen example for this attached to the documentation does not seem to work either. Is this an issue with the x-directives feature itself or a bug in the codepen? If x-directives is in fact working, are any directives supported other than mask?

**Comment by albanm** [comment]
X-directives simply apply directives that are available in your app. The doc does not state it, but the example relies on [v-mask](https://www.npmjs.com/package/v-mask). The codepen does not load v-mask which is why it is broken, but the example in the doc is not.

**Comment by Jared-Kim** [comment]
Thank You. Do you know if there is any way to trim whitespace from a string using x-directives?

**Comment by albanm** [comment]
It is a limitation of x-directives. You could trim whitespace by writing your own directive and applying it with x-directives.

**Comment by Jared-Kim** [comment]
Was able to figure it out, thanks for the help
