### ISSUE TITLE
schema should also be passed as a property of slot

### ISSUE THREAD

**Issue by agmoyano** [koumoul-dev/vuetify-jsonschema-form#43]
Actually if you modify fullSchema within a slot, nothing happens. That's because fullSchema is a computed property, when it could be returned in data.

Thanks

**Comment by agmoyano** [comment]
fullSchema is a computed property, so any changes in it are not reactive. We should pass schema as a property also to slot, in order to be able to modify schema on any given condition.

**Comment by agmoyano** [comment]
schema as it is a prop passed to Property it's not reactive for local changes.. for my particular use, I need to be able to change the schema within a slot and for things to happen in consecuence, but I doubt this is my particular use case.. 

This could be useful if combined with Issue #45, where in a prepend or append slot you change the schema, that affects the Property component in the default slot.

For this to happen, the schema prop should be assigned to a data variable like this

```javascript
data() {
  return {
    ...,
    localSchema: this.schema
  }
}
```

and then use it like this for each slot

```html
<slot :name="`prepend-${slotName}`" :schema="localSchema" .. />
```
and maybe use it to compute fullSchema

```javascript
   fullSchema() {
      return schemaUtils.prepareFullSchema(this.localSchema, this.modelWrapper, this.modelKey)
    }
```
If you agree to this I'll PR.

Thanks

**Comment by albanm** [comment]
Sorry for the delay, I will include this in the next major version I am working on.

**Comment by albanm** [comment]
v1 was released a short while ago with this functionality, see [this example](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#slots).
