### ISSUE TITLE
Behavior of optional objects with required fields

### ISSUE THREAD

**Issue by saveliy-sviridov** [koumoul-dev/vuetify-jsonschema-form#431]
It appears that this as of the current version of the library the problem described in [this issue](https://github.com/koumoul-dev/vuetify-jsonschema-form/issues/230) 
I was wondering if you've ever gotten around to exploring any possible solutions or even whether this seems at all solvable without rewriting the entire lib to you? I'm sadly not in a position to modify the schema in a way described in [this comment](https://github.com/koumoul-dev/vuetify-jsonschema-form/issues/230#issuecomment-816464315), so I'm trying to find an alternative way to resolve it.

**Comment by albanm** [comment]
This should be working ok in version 3 (currently 3.0.0-beta.6) for Vue/Vuetify 3. Won't be fixed in version 2.

**Comment by saveliy-sviridov** [comment]
Ah, that's my issue, I'm still on vue 2.
Thank you for your answer.
