### ISSUE TITLE
Have an option to silence logs

### ISSUE THREAD

**Issue by Q16solver** [koumoul-dev/vuetify-jsonschema-form#434]
Hello! I started using this library, and it's been working great so far! I was just wondering if there's an easy way of removing the console logs with compile options whenever the vjsf component gets mounted. maybe like an environment option or debug option? so I can turn it off in development/production when I need to reduce noise, thanks!

**Comment by albanm** [comment]
I will soon do a release that will remove this console.log. If useful I will use the [debug](https://www.npmjs.com/package/debug) module to add optional logs.

**Comment by Q16solver** [comment]
Seems to be removed now, thanks c:
