### ISSUE TITLE
Add support for radio (Vuetifiy components)

### ISSUE THREAD

**Issue by boutils** [koumoul-dev/vuetify-jsonschema-form#436]
Except if I am wrong, there is no way in `vjsf3` to display some radio buttons. Note that it seems achievable in `vjsf2`.
What is the best way to do this? Do I have to create my own plugin or you will add it soon?

![Screenshot 2024-05-31 at 10 06 08](https://github.com/koumoul-dev/vuetify-jsonschema-form/assets/1707229/d0aa48c8-a07f-4271-ae3a-ca0bb97309ce)

Thanks a ton!

**Comment by albanm** [comment]
I will try to add it soon.

**Comment by albanm** [comment]
Is this ok https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/selection/groups ?

**Comment by boutils** [comment]
Awesome! Thank you so much!
