### ISSUE TITLE
"Module not found" errors

### ISSUE THREAD

**Issue by tmatson98** [koumoul-dev/vuetify-jsonschema-form#446]
Hello,
Trying to install any version past beta 10 gives the following errors:

```
ERROR in ./node_modules/@json-layout/vocabulary/src/validate.js 1:0-40
Module not found: Error: Can't resolve 'ajv/dist/2019.js'
 @ ./node_modules/@json-layout/vocabulary/src/normalize.js 3:0-52 474:28-48
 @ ./node_modules/@json-layout/vocabulary/src/index.js 7:0-79 7:0-79 7:0-79
 @ ./node_modules/webpack-plugin-vuetify/dist/scriptLoader.js!./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[13].use[0]!./node_modules/@koumoul/vjsf/src/components/nodes/one-of-select.vue?vue&type=scri
pt&setup=true&lang=js 5:0-54 57:9-21 67:250-262
 @ ./node_modules/@koumoul/vjsf/src/components/nodes/one-of-select.vue?vue&type=script&setup=true&lang=js 1:0-211 1:0-211 1:212-412 1:212-412
 @ ./node_modules/@koumoul/vjsf/src/components/nodes/one-of-select.vue 2:0-75 3:0-70 3:0-70 6:49-55
 @ ./node_modules/webpack-plugin-vuetify/dist/scriptLoader.js!./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[13].use[0]!./node_modules/@koumoul/vjsf/src/components/vjsf.vue?vue&type=script&setup=true&l
ang=js 24:0-55 80:19-34 107:445-460
 @ ./node_modules/@koumoul/vjsf/src/components/vjsf.vue?vue&type=script&setup=true&lang=js 1:0-196 1:0-196 1:197-382 1:197-382
 @ ./node_modules/@koumoul/vjsf/src/components/vjsf.vue 2:0-66 3:0-61 3:0-61 8:49-55
 @ ./node_modules/@koumoul/vjsf/src/index.js 1:0-40 3:0-31 4:15-19
 @ ./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[13].use[0]!./src/components/Popups/Prompt.vue?vue&type=script&lang=js 8:0-33 20:10-14
 @ ./src/components/Popups/Prompt.vue?vue&type=script&lang=js 1:0-189 1:0-189 1:190-368 1:190-368
 @ ./src/components/Popups/Prompt.vue 2:0-57 3:0-52 3:0-52 9:49-55
 @ ./node_modules/webpack-plugin-vuetify/dist/scriptLoader.js!./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[13].use[0]!./src/App.vue?vue&type=script&setup=true
&lang=js 31:0-48 513:15-21
```

```
ERROR in ./node_modules/@json-layout/vocabulary/src/validate.js 3:0-34
Module not found: Error: Can't resolve 'ajv-errors' in
 @ ./node_modules/@json-layout/vocabulary/src/normalize.js 3:0-52 474:28-48
 @ ./node_modules/@json-layout/vocabulary/src/index.js 7:0-79 7:0-79 7:0-79
 @ ./node_modules/webpack-plugin-vuetify/dist/scriptLoader.js!./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[13].use[0]!./node_modules/@koumoul/vjsf/src/components/nodes/one-of-select.vue?vue&type=scri
pt&setup=true&lang=js 5:0-54 57:9-21 67:250-262
 @ ./node_modules/@koumoul/vjsf/src/components/nodes/one-of-select.vue?vue&type=script&setup=true&lang=js 1:0-211 1:0-211 1:212-412 1:212-412
 @ ./node_modules/@koumoul/vjsf/src/components/nodes/one-of-select.vue 2:0-75 3:0-70 3:0-70 6:49-55
 @ ./node_modules/webpack-plugin-vuetify/dist/scriptLoader.js!./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[13].use[0]!./node_modules/@koumoul/vjsf/src/components/vjsf.vue?vue&type=script&setup=true&l
ang=js 24:0-55 80:19-34 107:445-460
 @ ./node_modules/@koumoul/vjsf/src/components/vjsf.vue?vue&type=script&setup=true&lang=js 1:0-196 1:0-196 1:197-382 1:197-382
 @ ./node_modules/@koumoul/vjsf/src/components/vjsf.vue 2:0-66 3:0-61 3:0-61 8:49-55
 @ ./node_modules/@koumoul/vjsf/src/index.js 1:0-40 3:0-31 4:15-19
 @ ./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[13].use[0]!./src/components/Popups/Prompt.vue?vue&type=script&lang=js 8:0-33 20:10-14
 @ ./src/components/Popups/Prompt.vue?vue&type=script&lang=js 1:0-189 1:0-189 1:190-368 1:190-368
 @ ./src/components/Popups/Prompt.vue 2:0-57 3:0-52 3:0-52 9:49-55
 @ ./node_modules/webpack-plugin-vuetify/dist/scriptLoader.js!./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[13].use[0]!./src/App.vue?vue&type=script&setup=true
&lang=js 31:0-48 513:15-21
```

The problem seems to be that the `@json-layout/vocabulary` package is trying to use `ajv-errors` but doesn't list it as a dependency, and that `ajv` is listed in `devDependencies` instead of `dependencies`. Since this is how it's set up in `@json-layout/core` I copied it's `node_modules` to the vocabulary package and it worked after that.

**Comment by albanm** [comment]
Can you try the latest beta 42 ?

**Comment by phoenix-oes** [comment]
```
SyntaxError: The requested module '/@fs/workspaces/opendso-gms-applications/node_modules/.pnpm/ajv-formats@2.1.1_ajv@8.17.1/node_modules/ajv-formats/dist/index.js?v=8c817196' does not provide an export named 'default' (at validate.js?v=8c817196:2:8)
```

This is what I get when trying beta 42

**Comment by albanm** [comment]
Yes, these errors are a pain, it comes from the mix of ESM and CommonJS dependencies. You can try tuning the optimizeDeps.includes and build.commonjsOptions.includes options. I provide [these](https://github.com/json-layout/json-layout/blob/main/core/src/utils/build.js) to try to help solving these problems. I suppose commonjsDepsPaths is missing something like ['@json-layout/vocabulary', 'ajv-formats'], maybe you can try completing it.

Things vary depending on the build system and the use of an installer that either nests of flatten the dependencies directories. So I don't know how to test and provide a fixall solution. Ideally the maintainer of ajv would switch to exporting ESM modules at some point.

**Comment by albanm** [comment]
Maybe I should declare these as dependencies in json-layout/core and peer dependencies in json-layout/vocabulary so that the access paths are not duplicated.

**Comment by tmatson98** [comment]
Beta 42 fixed it for me, thank you!

**Comment by phoenix-oes** [comment]
> Yes, these errors are a pain, it comes from the mix of ESM and CommonJS dependencies. You can try tuning the optimizeDeps.includes and build.commonjsOptions.includes options. I provide [these](https://github.com/json-layout/json-layout/blob/main/core/src/utils/build.js) to try to help solving these problems. I suppose commonjsDepsPaths is missing something like ['@json-layout/vocabulary', 'ajv-formats'], maybe you can try completing it.

The [Vite config example](https://github.com/koumoul-dev/vuetify-jsonschema-form/blob/master/app-examples/vite-typescript/vite.config.ts) has those parts of the config commented out. When trying to use them locally, `commonjsOptions` complains that it is expecting an array of strings, not a 2D array of string pairs. What's the right way to use those settings?

**Comment by Kaschi14** [comment]
For some reason I needed to add "ajv-formats/dist" to make it work. Also i resolved the nested arrays like this:

`optimizeDeps: {
    include: [
      'ajv',
      'ajv/dist/2019.js',
      'ajv-formats',
      'ajv-formats/dist',
      'ajv-formats/dist/formats.js',
      'ajv-errors',
      'markdown-it',
      'ajv-i18n',
      'debug',
      
    ],
  },
  build: {
    commonjsOptions: {
      include: [
        '@json-layout/core/ajv',
        '@json-layout/core/ajv/dist/2019.js',
        '@json-layout/core/ajv-formats',
        '@json-layout/core/ajv-formats/dist',
        '@json-layout/core/ajv-formats/dist/formats.js',
        '@json-layout/core/ajv-errors',
        '@json-layout/core/markdown-it',
        '@json-layout/core/ajv-i18n',
        '@json-layout/core/debug',
      ],
    },
  },`
  
I'm using the latest beta42 and the latest npm. 

However for some reasons adding these options to my vite script resulting in my vite build to throw errors in completely different packages, e.g.:
`default" is not exported by "node_modules/crypto-js/index.js", imported by "src/modules/utils.js".
file:  /src/modules/utils.js:2:7
1: import axios from 'axios';
2: import CryptoJS from 'crypto-js';
          ^`
          
I guess this is more a vite issue, but maybe anyone has an idea.

**Comment by albanm** [comment]
Thanks ! I will add this to the documentation.

**Comment by phoenix-oes** [comment]
Unfortunately I still get an error, still with ajv, which looks like your previous error

```console
[Vue Router warn]: Unexpected error when starting the router: SyntaxError: The requested module '/@fs/workspaces/opendso-gms-applications/node_modules/.pnpm/ajv-formats@2.1.1_ajv@8.17.1/node_modules/ajv-formats/dist/index.js?v=d075ec3a' does not provide an export named 'default' (at validate.js?v=d075ec3a:2:8)
```

:disappointed:

**Comment by Kaschi14** [comment]
@phoenix-oes 
Can you copy optimizeDeps and commonsJsOptions of your vite.config.js? 

Just to be clear, this is how mine looks like now:

```
export default defineConfig({
  optimizeDeps: {
    include: [
      'ajv',
      'ajv/dist/2019.js',
      'ajv-formats',
      'ajv-formats/dist',
      'ajv-formats/dist/formats.js',
      'ajv-errors',
      'ajv-i18n',
      'markdown-it',
      'debug',
      'jdenticon',
      'vue3-markdown-it',
      'json-source-map',
      'jmespath',
      'natural-compare-lite',
      'jszip',
    ],
  },
  build: {
    commonjsOptions: {
      transformMixedEsModules: true,
    },
  },
```

All optimizeDeps packages have are or have commonjs dependencies.

**Comment by haayman-imagem** [comment]
> Can you try the latest beta 42 ?

beta 42 of which package? Can't find anything that has this release
