### ISSUE TITLE
Export Property to be reachable by slots

### ISSUE THREAD

**Issue by agmoyano** [koumoul-dev/vuetify-jsonschema-form#45]
Actually I have a situiation where the default slot of a form should be displayed depending on variables outside the schema (and should not be placed in schema either), but the prepend slot should always remain visible. 

I cannot use x-class or x-display because they affect the v-flex surrounding prepend, default and append slots. 

I thought in proposing changes in schema that only affects a certain slot, but It will get messy, and this case is extremly particular.

What I propose is to export Property in index.vue, so someone could just simply 

```javascript

import VJsonschemaForm, { Property } from '@koumoul/vuetify-jsonschema-form'

```
and use _Property_ within a slot.

This would mean that any data needed for Property, should also be passed to the slot.

Thanks

**Comment by albanm** [comment]
It seems ok to me.

But be aware that you will make your code dependent on what I consider to be internals of the library, some breakage will probably happen in future releases. I am ok with opening this kind of possibilities,  just don't expect it to be maintained in the same way as the actual functionalities.

**Comment by albanm** [comment]
About exposing Property, maybe we can keep the built lib as it is and the people who want to do this should load the lib from source ?

Personally I always load the lib from source as it works well with vuetify-loader, like this:

```
import VJsonschemaForm from '@koumoul/vuetify-jsonschema-form/lib/index.vue'
```

**Comment by agmoyano** [comment]
I really didn't try to 

```javascript
import Property from '@koumoul/vuetify-jsonschema-form/lib/components/Property.vue'
```
If that's possible, maybe we don't need to do anything

I'll let you know

**Comment by albanm** [comment]
You will need to instruct your built tool to process this file.

In webpack it should look like this:

```
transpile: ['vuetify', /@koumoul/], // Necessary for "à la carte" import of vuetify components
```

**Comment by agmoyano** [comment]
I'm using nuxt, so I didn't have to do anything. It worked!!.. now what's remaining is to pass the necesary properties to slots, and that's it

Thanks!

**Comment by albanm** [comment]
Please note that in v1 the Property component doesn't exist anymore. Instead the VJsf component is recursive and each property is a new instance of the same component. Still this kind of thing should be doable in a similar manner.
