### ISSUE TITLE
I want to add a placeholder to a text field, but it isn't working

### ISSUE THREAD

**Issue by activeliang** [koumoul-dev/vuetify-jsonschema-form#450]
I need some advice: I want to add a placeholder to a text field, but it isn't working. I want the placeholder to be displayed without showing the table.

Here is my code:

``` vue
<template>
  <div>
    <v-form>
      <vjsf v-model="data" :schema="schema" :options="options"></vjsf>
    </v-form>
  </div>
</template>
<script setup>
import { ref } from 'vue'
const data = ref({})
const schema = ref({
  type: 'object',
  properties: {
    text: {
      type: 'string',
      title: '',
      layout: {
        props: {
          appendIcon: 'mdi-heart',
          placeholder: 'my placeholder'
        }
      }
    }
  }
})
const options = ref({
  context: {},
  width: '100%',
  summary: true,
  density: 'compact',
  autofocus: true,
  locale: 'en'
})
</script>
```

Where should I set the placeholder if I want it to be displayed?

**Comment by albanm** [comment]
Yes, sorry about that, there was a bug. The placeholder was supposed to be defined directly in layout but it was broken and the one in layout.props was ignored. Now both should be possible.

**Comment by activeliang** [comment]
Here’s a refined English version:

"You're amazing! You're the quickest problem-solver I've come across on GitHub. I've spent the last five hours debugging and backtracking while trying to learn about json-layout, but my progress was minimal, and I was getting frustrated. Then I saw your reply in my inbox. Thank you so much for sharing such a useful project!"

**Comment by albanm** [comment]
Thanks !

Unfortunately the code is pretty complex with multiple layers. It makes sense for me as the author, but I am not surprised that it was hard for you to find the cause of your problem.
