### ISSUE TITLE
Feedback: When using a select component inside a dialog, there is a z-index issue with the dropdown menu.

### ISSUE THREAD

**Issue by activeliang** [koumoul-dev/vuetify-jsonschema-form#453]
![WX20240903-151013@2x](https://github.com/user-attachments/assets/4ed21bc1-7eb8-4663-958d-d0a4183f547f)

As shown in the image, the dialog has a z-index of 2400, but the automatically generated dropdown menu of the select component has a z-index of 2000, causing it to be covered. I tried manually adding a Vuetify select component inside the dialog, and I found that its dropdown menu has a z-index of 2410, displaying correctly.

**Comment by albanm** [comment]
Sorry about that, I let this issue go stale while it was a real problem. Vuetify uses internally a useStack composable to manage increments to z-index. This composable is somewhat buggy.

I solved this in the latest release by overriding the z-index of selects, auto-completes and menus, setting it to 3000. I hope this works in all cases.
