### ISSUE TITLE
How can I compile a schema when it needs to be generated dynamically?

### ISSUE THREAD

**Issue by activeliang** [koumoul-dev/vuetify-jsonschema-form#454]
I need to dynamically modify the schema based on the response from an API request. However, as per the documentation, when [compiling at build time](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/getting-started), a complete schema and options need to be provided for it to compile correctly. Do you have any suggestions for handling schemas that need to be generated dynamically?

**Comment by albanm** [comment]
This is why there are 2 modes. Unless I misunderstand something, in your case it is the compile at runtime that is needed. The standard vjsf component should be reactive to the schema.

**Comment by activeliang** [comment]
I see, it looks like I should look into Compile at runtime. The package size is quite large due to this, and I'm not very familiar with tree-shaking and minifying.
