### ISSUE TITLE
(!) Could not auto-determine entry point from rollupOptions or html files [...] when trying to include CommonJS Dependecies

### ISSUE THREAD

**Issue by Lienhop** [koumoul-dev/vuetify-jsonschema-form#461]
Hi! I am sure this is an error on my part,  but when trying to recreate a minimum example from the docs I am receiving the following Error as soon as I `import { Vjsf } from '@koumoul/vjsf';`. The CommonJS dependencies should be included.

`Uncaught SyntaxError: The requested module 'http://localhost:5173/node_modules/@json-layout/vocabulary/node_modules/ajv-errors/dist/index.js?v=768ce2d9' doesn't provide an export named: 'default'`

Anybody have encountered this issue before?

**Comment by albanm** [comment]
Dit you look at the "CommonJS dependencies" section in the [getting-started](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/getting-started) ?

**Comment by Lienhop** [comment]
Alright I solved the issue. It was just necessary to manually install the ajv library via

```
npm i ajv
npm i ajv-errors
npm i ajv-i18n
npm i ajv-formats
```

which solved the problem.

**Comment by albanm** [comment]
This should not have been necessary. But the way modules are nested can change the necessary optimizeDeps options, it is a bit of a mess. I suppose installing the modules yourself changed the way they are nested in your node_modules and fixed the problem in your case.
