### ISSUE TITLE
Set readOnlyPropertiesMode for specific Attribute

### ISSUE THREAD

**Issue by Kaschi14** [koumoul-dev/vuetify-jsonschema-form#462]
I want to hide a single "readOnly" attribute, but keep the global options as default ("show").
In the docs I read that it can be achieved "locally" via layout.options.
However I wasn't able to make it happen.
Currently my schema for the attribute looks like this:
```
"host": {
  "title": "Host",
  "type": "string",
  "readOnly": true,
  "layout": {
    "options": {
      "readOnlyPropertiesMode": "hide"
    }
  }
}
```

I also tried some other variations.
Thanks in advance :)

**Comment by albanm** [comment]
This is a limitation. The way things work for now, the option is applied on the children of a node not from a node to itself. So that the option must be defined on the parent object.
