### ISSUE TITLE
Slots misbehaving on OneOf/AllOff

### ISSUE THREAD

**Issue by jcricaro** [koumoul-dev/vuetify-jsonschema-form#52]
Prepend and append doesn't work on OneOf and AllOf properties, they work fine on normal properties tho. `v-slot:property` also doesn't replace referenced properties.

**Comment by jcricaro** [comment]
Okay, the slot name changes depending on the depth of property,

mine resolved to:

```
append-allOf-0.patient
```

**Comment by albanm** [comment]
Sorry for the lack of response.

I know I need to work on documentation for this kind of stuff.
