### ISSUE TITLE
'oneOf' field const = 0 doesn't work when number type property

### ISSUE THREAD

**Issue by d0ng13** [koumoul-dev/vuetify-jsonschema-form#53]
'oneOf' field const = 0 doesn't work when number type property.
like this:
"P1": {
	"type": "number",
	"title": "P1-t",
	"oneOf": [ 
		{ "const": 0, "title": "T0" },
		{ "const": 1, "title": "T1" }
	]
}
when I select 'T0', return is error val "T0"(string), but 'T1', return is correct val 1.

**Comment by HochulCL** [comment]
For a temporary solution this is what I did
`“oneOf”: [
        {
          “enum”: [
            0
          ],
          “const”: 0,
          “title”: “Percentage”
        },
        {
          “const”: 1,
          “title”: “Absolute”
        }
      ]`

put   “enum”: [0], in the item which uses const value 0 since source code is checking 0 value and do something.
