### ISSUE TITLE
Action on input

### ISSUE THREAD

**Issue by Cirrusware** [koumoul-dev/vuetify-jsonschema-form#55]
Hello,

I need to add an action next to an element.
Example: <input type="email"> <a href="" class="btn">My action</a>

How to proceed ?

Thanks a lot.

**Comment by albanm** [comment]
There is a slot mechanism that can be used to add contents before or after some properties. Could this work for you ?

**Comment by Cirrusware** [comment]
Nice.

Have you an example ?

**Comment by albanm** [comment]
Documentation is lacking, but here are some examples https://github.com/koumoul-dev/vuetify-jsonschema-form/blob/master/demo/DemoApp.vue#L60

**Comment by Cirrusware** [comment]
It's already great.

Thanks a lot.

**Comment by Cirrusware** [comment]
Hello, I try with slots but it'not really as I would like.

Maybe more like that

<v-text-field
            :append-icon="marker ? 'mdi-map-marker' : 'mdi-map-marker-off'"
            :append-outer-icon="message ? 'mdi-send' : 'mdi-microphone'"
            :prepend-icon="icon"
            @click:append="toggleMarker"
            @click:append-outer="sendMessage"
            @click:prepend="changeIcon"
            @click:clear="clearMessage"

![image](https://user-images.githubusercontent.com/5724417/70375412-c9d20c00-18fd-11ea-9065-67121063a55a.png)

What do you think?

**Comment by Cirrusware** [comment]
Ok I have a solution

![image](https://user-images.githubusercontent.com/5724417/70376001-cc842f80-1904-11ea-9385-8dc6d155e6ec.png)


```html
<template v-slot:append-inner-custom-tel="{ model }">
                    <div class="text-right">
                        <v-btn @click="actionTel(model)" text icon x-small>
                            <v-icon>fas fa-phone</v-icon>
                        </v-btn>
                    </div>
                </template>
```

In your Property.vue
```html
<!-- Simple text field -->
<v-text-field v-else-if="fullSchema.type === 'string'"
                    v-model="modelWrapper[modelKey]"
                    :name="fullKey"
                    :label="label"
                    :disabled="disabled"
                    :readonly="readOnly"
                    :required="required"
                    :rules="rules"
                    @change="change"
                    @input="input"
      >
        <tooltip slot="append-outer" :options="options" :html-description="htmlDescription" />
        <template slot="append">
          <slot :name="`append-inner-${slotName}`" :fullKey="fullKey" :fullSchema="fullSchema" :modelWrapper="modelWrapper" :modelKey="modelKey" :model="modelWrapper[modelKey]" :required="required" :disabled="disabled" :rule="rules" :htmlDescription="htmlDescription" />
        </template>

      </v-text-field>
```

**Comment by albanm** [comment]
Ok, but adding a bunch of slots to all the sorts of fields supported will increase the verbosity of Property.vue. And it is already pretty high.

So this issue is part of the drive for building a new major version, cf https://github.com/koumoul-dev/vuetify-jsonschema-form/issues/56. I hope to have it working and released in about 2 weeks.

In the mean time if you are in a hurry you might want to use a temporary fork with you modifications.

**Comment by Cirrusware** [comment]
No problem. I use npx patch-package for that.

Thanks a lot.

**Comment by albanm** [comment]
v1 was released a short while ago with this functionality, see [this example](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#slots).
