### ISSUE TITLE
Text (not editable) property

### ISSUE THREAD

**Issue by flaviocordova** [koumoul-dev/vuetify-jsonschema-form#59]
Is there a way to add a text as a property in the form? Just like you can get when setting form description but anywhere in the form and as many times as I wish.

**Comment by albanm** [comment]
You can't simply define this content in the schema, but you can add content before or after a property using slots. cf https://github.com/koumoul-dev/vuetify-jsonschema-form/blob/master/demo/DemoApp.vue#L60

This is not properly documented and is expected to change slightly in the v1 coming soon.
