### ISSUE TITLE
 After build (production mode), some elements of VJsonschemaForm are not displayed.

### ISSUE THREAD

**Issue by KammerR** [koumoul-dev/vuetify-jsonschema-form#62]
When I use it in development mode, it normally loads form elements. But when I build for the production version, some elements and even whole fields do not appear.

I had a similar problem with v-currency-field, which did not appear in the build. After an update, they put a treeshake module into nuxt and it loaded normally. I think that might be the case too (or a way to solve the problem)

I have a project where I perform some tests and in it, on the page "inspire.vue", in production mode, I can see the error

[https://github.com/KammerR/nuxtVcurrencyBuild/tree/master/basicNuxt](url)

A screenshot to see what happens in production mode
![Captura de tela de 2020-01-13 15-30-20](https://user-images.githubusercontent.com/50989673/72281643-acd5da80-3619-11ea-9299-61ada2daee36.png)

**Comment by albanm** [comment]
With nuxt you should use `import VJsonschemaForm from '@koumoul/vuetify-jsonschema-form/lib/index.vue'`. This way vuetify-loader (use by the nuxt vuetify plugin tu perform "à la carte" loading) will detect the vuetify components that vjsf depends on.

**Comment by KammerR** [comment]
When I use this setting in development mode, it doesn't work

![Captura de tela de 2020-01-13 16-39-11](https://user-images.githubusercontent.com/50989673/72286124-45bd2380-3623-11ea-9263-5b8ec197d2e5.png)

**Comment by albanm** [comment]
ah yes, you might have to configure your build to transpile vjsf as it does to your source code. It should look like this in your nuxt.config.js :

```
build: {
    transpile: [/@koumoul/], // Necessary for "à la carte" import of vuetify components used by vjsf
}
```

**Comment by KammerR** [comment]
So ... I made the following modifications

I modified the import to `import VJsonschemaForm from '@koumoul / vuetify-jsonschema-form / lib / index.vue'` and put the transpile setting in the build as you passed me.

However, due to the page loads the form, but without some components and in production most components disappear too, leaving only a few.

I removed other libraries to only test VjsonSchemaForm, all changes are in the project mentioned above. Thank you in advance for your help!

Dev(Here the tooltips and icons don't appear, and the fields didn't work as they should.)
![Captura de tela de 2020-01-14 18-32-28](https://user-images.githubusercontent.com/50989673/72384632-9ce2f700-36fc-11ea-82bc-0384a1764a1b.png)

Prod(Here they totally bugged)
![Captura de tela de 2020-01-14 18-33-54](https://user-images.githubusercontent.com/50989673/72384680-b84e0200-36fc-11ea-956e-f7c1f9e361b1.png)

@albanm

**Comment by KammerR** [comment]
Hello! I was able to solve this problem by globally importing all the vuetify components used by JsonSchemaForm

As in the code below

```
import Vue from 'vue'
import {
  VTooltip,
  VIcon,
  VListItem,
  VAvatar,
  VFlex,
  VLayout,
  VSelect,
  VTextarea,
  VCheckbox
} from 'vuetify/lib'

Vue.component('v-tooltip', VTooltip)
Vue.component('v-icon', VIcon)
Vue.component('v-list-item', VListItem)
Vue.component('v-avatar', VAvatar)
Vue.component('v-flex', VFlex)
Vue.component('v-layout', VLayout)
Vue.component('v-select', VSelect)
Vue.component('v-textarea', VTextarea)
Vue.component('v-checkbox', VCheckbox)
```
