### ISSUE TITLE
Question regarding div

### ISSUE THREAD

**Issue by amz4u2nv** [koumoul-dev/vuetify-jsonschema-form#63]
Hi, really like this library, just had a question - 
is it possible to assign different elements (textfields, selects,  etc) to different divs. 
some elements would then go to class A and some class B, so that the structure of the form can be designed via divs.

```
<v-form>
<div class = 'A'>
</div>
<div class = 'B'>
</div>
</v-form>
```

Thanks

**Comment by albanm** [comment]
No, this is not supported, and I don't see an easy way of doing it.

What can be done is using allOfs to separate properties in groups without changing the underlying structure of the schema. These groups can be represented as foldable sections (https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/?example=combinations), accordions (https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/?example=accordion) or tabs (https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/?example=tabs).
