### ISSUE TITLE
Const depending on an other input value

### ISSUE THREAD

**Issue by tg44** [koumoul-dev/vuetify-jsonschema-form#64]
Hy!

I want to assign one form value to more output values. For example for the output of:
```
{
  "this": {"createdAt": ""},
  "that": {"createdAt": ""},
}
```
I want only one "createdAt" input on the form, but want to assign the same value to both sub element.
As I googled [const with $data](https://stackoverflow.com/questions/27907722/is-it-possible-in-json-schema-to-define-a-constraint-between-two-properties) had this thing in the past.

**Comment by albanm** [comment]
Hello,

I am in the middle of a big rewrite. This kind of functionality might make it into the next version but it won't be before a few weeks and I don't want to spend time on changes in the current version.

But feel free to submit a PR if you want.

**Comment by albanm** [comment]
I think this is really too much of an edge case with potential for a lot of extra complexity. It should be handled by the application, not this lib.
