### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by vdvpie22** [koumoul-dev/vuetify-jsonschema-form#65]
Where I can add error messages from ajax response?

**Comment by albanm** [comment]
I don't really understand your question. What ajax response are you talking about, something sent from the library, or something sent by your code using the object produced by the library ?

**Comment by vdvpie22** [comment]
I send object produced by the library in my code via ajax request to php controller with hard logic for validation, php controller can return object with errors. How I can add this errors to form? Where i can see validation params?

**Comment by albanm** [comment]
The lib provides a few validation rules (required, min, max..) that it uses to validate individual fields. This validity is propagated to the enclosing vuetifyjs form, so it is a bottom to top approach while you describe a top to bottom approach.

Your errors include the key of the invalid fields ? What you want is a way to overwrite the error and error-messages props of the fields based of their key in the sceham (cf https://vuetifyjs.com/en/components/text-fields) ?

It is not supported. I will think about it, maybe something like this can be included in the incoming major version. But honestly it won't come fast, at least a few weeks.

**Comment by vdvpie22** [comment]
Thank you for fast answer. 
Response included key with array error messages.
Example:
{
  email: ['The email field is required', 'The email field must be a valid email'],
  name: ['The email field is required'],
  age: ['The age field must be a valid number'],
}

I plan to use vee-validate to expand validation functionality of the form.
https://logaretm.github.io/vee-validate/advanced/server-side-validation.html#setting-errors-manually

**Comment by albanm** [comment]
I think the feature I just released for custom validation using either regexps or functions covers this use case. See [this example](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#validation-basic).

**Comment by vdvpie22** [comment]
Thank you, very good solution

**Comment by pjankiewicz** [comment]
In case someone is looking for an alternative solution. I had the same problem and ended up using slots:

In the template:
```html
<v-jsf v-model="model" :schema="vjsfSchema" :options="options">
    <template v-for="(_, key) in properties" :slot="key + '-after'">
       {{ errorMessagesDict[key] }}
    </template>
</v-jsf>
```

In the script

```javascript
api
  .post(..., this.model)
  .then(() => {
    ...
  })
  .catch(error => {
    var response = error.response.data;
    this.errorMessages = response;
    Object.keys(response).forEach(field => {
      this.errorMessagesDict[field] = response[field];
    });
  });
```

It works perfectly. Thank you for creating such a good project.

**Comment by avido** [comment]
> I think the feature I just released for custom validation using either regexps or functions covers this use case. See [this example](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#validation-basic).

Thanks for the update.. However i don't see how this can be implemented with backend validation (after/on form submit). 
Some validation can not be done upfront. (availability / unique db checks for instance). 

My backend validates the input and if not satisfied returns an array with errors. 
For instance:
```json
{"errors":{"sku":["The sku is already taken."]}}
```

Normally my solution (with vuetify) i use the property `:error-messages` and on submit i catch the errors and update the binded model. 

Small example:
```
try {
    let result = await this.$axios.post(endpoint, this.model);
} catch (err) {
    if (err.response.status === 422) {
        this.validationState = err.response.data.errors;
    }
}
``` 

Any ideas on how to accomplish this functionality ?
