### ISSUE TITLE
readonly field

### ISSUE THREAD

**Issue by amz4u2nv** [koumoul-dev/vuetify-jsonschema-form#68]
Would it be possible to add read only field per property - 
    disabled() {
      return this.options.disableAll
    },
    return this.fullSchema['x-disable']

**Comment by albanm** [comment]
Sorry for the delay. It will be possible in the next major major I am working on.

**Comment by albanm** [comment]
v1 was released a short while ago with this functionality, see [this example](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#read-only).
