### ISSUE TITLE
Is it possible to use x-options per object item and not only globally?

### ISSUE THREAD

**Issue by jousepo** [koumoul-dev/vuetify-jsonschema-form#69]
Hello,
how can i draw a tab inside another tab or an accordion inside a tab or viceversa?

When i apply a allOfTab: true in the 'x-options' only the first allOf is displayed as a tab but childrens not.

Thanks in advance

**Comment by albanm** [comment]
Not possible in the current version, sorry.

**Comment by jousepo** [comment]
Hope you implement this in the near future but enough for now.

Thanks!!!

**Comment by albanm** [comment]
Yes, it will be possible to have tabs and accordions at multiple levels in the next major version.

**Comment by albanm** [comment]
I reopen this issue to attach it to the next milestone.

**Comment by jousepo** [comment]
Thanks!!!! However, i found a temporary solution (if anyone needed).
After configuring the **allOfTab** to _true_ if you put an object containing and allOf item without **title** their components will be displayed normally.

Here it is the tabs demo modified to prove the facts:

`{
  "$id": "https://example.com/person.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Combinations",
  "description": "Rendering a root allOf as tabs",
  "type": "object",
  "x-options": {
    "allOfTabs": true
  },
  "allOf": [
    {
      "$ref": "#/definitions/realWorldEntity"
    },
    {
      "$ref": "#/definitions/socialMediaEntity"
    }
  ],
  "definitions": {
    "realWorldEntity": {
      "properties": {
        "address": {
          "type": "string",
          "maxLength": 2000
        },
        "credit_card": {
          "type": "number"
        }
      },
      "dependencies": {
        "credit_card": {
          "properties": {
            "billing_address": {
              "type": "string"
            }
          },
          "required": [
            "billing_address"
          ]
        }
      }
    },
    "socialMediaEntity": {
      "properties": {
        "twitter": {
          "type": "string"
        },
        "facebook": {
          "type": "string"
        }
      }
    }
  }
}`

**Comment by albanm** [comment]
functionality available in v1, see the parts about [sections management in the doc](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#sections).
