### ISSUE TITLE
File input

### ISSUE THREAD

**Issue by msurguy** [koumoul-dev/vuetify-jsonschema-form#7]
Hi! Thank you so much for this repository, it is a very good start towards composable forms and CMS systems!

I was wondering what kind of options I would have if I wanted to implement file input in the JSON schema format and what changes I'd have to make in order to create a new transformer for file input field. Moreover, I am wondering how to deal with async data and how to populate the model with the results of file uploading / cropping / etc. Any details on that would be very helpful.

Thank you!

**Comment by albanm** [comment]
Hello,

I understand the need to compose more complete forms, but I don't see how the result of a file upload would be represented in the resulting model. Do you mean to write the content of the file serialized in base64 in a string field ? Or do you mean to associate an array of File objects next to the json model ?

The first case seems like a suboptimal way of dealing with binary content. The second means that the json schema is not really the proper place to describe the expected files.

I suppose an intermediate solution could be to store the uploaded files next to the model, and in the model to store a "link" a small object containing some metadata (filename, mimetype) of the uploaded file.

**Comment by msurguy** [comment]
@albanm I envision a couple use cases for a CMS I'm building:
- Small SVG file upload
- Large JPEG/PNG file upload

I was able to get the first use case implemented by doing base64 conversion of the SVG icons (I'll provide an example here) but because I don't know a better way, it could probably be improved .

For the second use case, the files would be uploaded and a URL string would be returned pointing to the file. I simply was looking for your input on how I would add some new fields that rely on time-consuming tasks like file upload. 

Without further ado, here's my code for the inline SVG example.

Property:
```
 'properties': {
      'svg': {
        'type': 'file',
        'description': 'The File that you want to have.'
      }
    }
```

Add a new file type Property
```
    <!-- SVG File picking -->
    <div v-else-if="fullSchema.type === 'file'"
         :required="required"
         :rules="rules">
      {{ fullKey }} {{ label }}
      <v-tooltip v-if="fullSchema.description" slot="append" left>
        <v-icon slot="activator">info</v-icon>
        <div class="vjsf-tooltip" v-html="htmlDescription"/>
      </v-tooltip>
      &nbsp;&nbsp;
      <v-flex xs12 class="text-xs-center text-sm-center text-md-center text-lg-center">
        <file-picker v-model="modelWrapper[modelKey]" />
      </v-flex>
    </div>
```

FilePicker.vue
```
<template>
  <div>
    <img v-if="imageUrl" :src="imageUrl" height="150">
    <v-text-field label="Select Image" prepend-icon="attach_file"
                  @click="pickFile"/>
    <input
      ref="image"
      type="file"
      accept="image/*"
      @change="onFilePicked"
    >
  </div>
</template>

<script>
export default {
  name: 'FilePicker',
  model: {
    prop: 'imageUrl',
    event: 'change'
  },
  props: {
    imageUrl: {
      type: String,
      default: ''
    }
  },
  data: () => ({
    imageName: '',
    imageFile: ''
  }),
  methods: {
    pickFile() {
      this.$refs.image.click()
    },
    onFilePicked(e) {
      const files = e.target.files
      if (files[0] !== undefined) {
        this.imageName = files[0].name
        if (this.imageName.lastIndexOf('.') <= 0) {
          return
        }
        const fr = new FileReader()
        fr.readAsDataURL(files[0])
        fr.addEventListener('load', () => {
          // this.imageUrl = fr.result
          this.imageFile = files[0] // this is an image file that can be sent to server...
          this.$emit('change', fr.result)
        })
      } else {
        this.imageName = ''
        this.imageFile = ''
        this.imageUrl = ''
      }
    }
  }
}
</script>
```

**Comment by albanm** [comment]
I worked on the File feature, see [this example](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#files). I hope it covers most use cases, feel free to reopen and discuss it not.
