### ISSUE TITLE
Using "dense" prop in input fields

### ISSUE THREAD

**Issue by OdiljonQurbon** [koumoul-dev/vuetify-jsonschema-form#70]
Awesome project! Thank you.
Is it possible to use vuetify's  "dense" prop in input fields? For the time being I'm using css to reduce the input height, but would be great if I could use dense.

**Comment by albanm** [comment]
It will be possible in the next major version that I currently work on.

**Comment by OdiljonQurbon** [comment]
Cool, thanks!

**Comment by OdiljonQurbon** [comment]
Probably it should stay opened until the v1 is published.

**Comment by albanm** [comment]
v1 was released a short while ago with this functionality, using the [fieldProps option](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/configuration).
