### ISSUE TITLE
Where is the detailed specification?

### ISSUE THREAD

**Issue by profikart** [koumoul-dev/vuetify-jsonschema-form#71]
Hi,

I was looking for specifications for properties, schema and options. I would like to know what parameters are available. I also can't create an email field, switch field.

Marcin

**Comment by albanm** [comment]
The documentation is lacking. For now the best ressource is the [demo page and its examples](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/?example=basic). Upcoming major version will improve on this aspect.

There is no switch or email field.
