### ISSUE TITLE
Documentation about json schema and which properties to be use in schema?

### ISSUE THREAD

**Issue by Nik720** [koumoul-dev/vuetify-jsonschema-form#72]
Where can I found proper documentation about JSON schema for all the fields and properties which I can use?
Please provide some reference links

**Comment by albanm** [comment]
The documentation is lacking. For now the best ressource is the [demo page and its examples](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/?example=basic). Upcoming major version will improve on this aspect.
