### ISSUE TITLE
Using autocomplete for oneOf inputs

### ISSUE THREAD

**Issue by gudirut** [koumoul-dev/vuetify-jsonschema-form#73]
Hello,
is it possible to use v-autocomplete for a oneOf list?
Having more than 20 entries in a v-select seems to be quite inconvenient.
Would be nice to have the option to choose between autocomplete and select.

Thank you in advance!

**Comment by albanm** [comment]
Not possible in current version. Supported by incoming major version, see [in this example](https://koumoul-dev.github.io/vuetify-jsonschema-form/render-functions/examples#select).

**Comment by albanm** [comment]
v1 was released a short while ago with this functionality
