### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by sobrinho** [koumoul-dev/vuetify-jsonschema-form#79]
Hey!

It would be nice to have a changelog between releases to avoid comparing the source.

**Comment by albanm** [comment]
Yes, I need to get better at this.

I just started using the [releases](https://github.com/koumoul-dev/vuetify-jsonschema-form/releases/tag/v1.4.0) page of github. I will try to keep this habit, if I do it I will reference this page in the doc later on.
