### ISSUE TITLE
Hide Fields

### ISSUE THREAD

**Issue by blasta19** [koumoul-dev/vuetify-jsonschema-form#8]
Hello, is there a way to hide fields on form from json schema using your plugin?

btw, this is awesome! You saved us a lot of time! 

Thank you!

**Comment by albanm** [comment]
Hello,

I just added a x-display=hidden value that you can define on a property to hide it. I also published a small release with this commit.

I don't know if there is some more standard json-schema annotation that would match this purpose. Tell me if you have an idea.

**Comment by blasta19** [comment]
hello Alban, thank you for the update, it works like a charm, one question, is there a way on how I can add grid option where a user can hardcode a grid per field?

Thanks again!

**Comment by glikoz** [comment]
> Hello,
> 
> I just added a x-display=hidden value that you can define on a property to hide it. I also published a small release with this commit.
> 
> I don't know if there is some more standard json-schema annotation that would match this purpose. Tell me if you have an idea.

Both of them implement as `options: { "hidden":"true}` 

https://github.com/jdorn/json-editor/issues/237

https://gist.github.com/ddohler/af5136a73e3be16ffaff40fa0f2117c7
