### ISSUE TITLE
Vuetify 2 and Typescript

### ISSUE THREAD

**Issue by toddsampson** [koumoul-dev/vuetify-jsonschema-form#80]
Thanks for all the great work on Vuetify JSONSchema Form so far. Love the idea! That said, I've run into a few issues actually using the library.,,

1) I am getting errors around the use of `v-flex` in the components, which was replaced by v-col in Vuetify 2.x. Are there plans to upgrade the library to work with Vuetify 2.x?

2) I didn't see any typescript type declarations in the code. Any plans to add typescript support? If so, it would be great to get some examples using class-based Vue components.

**Comment by albanm** [comment]
The library works with vuetify 2. The v-flex messages are only warnings if I am not mistaken. I will try to get rid of these messages soon.

I don't use typescript and I don't intend to. But a pull request is always welcome.

**Comment by toddsampson** [comment]
Thanks for the quick reply albanm. I thought I saw an error on the v-flex stuff, but it very easily could have been a warning. I removed the code temporarily since I'm up against a deadline, but will try it again to let you know for sure if I get time.

I use typescript in my projects these days, but haven't contributed types to a public project. If I get the types fleshed out for my project, I'll be sure to package them up as a a PR.

**Comment by albanm** [comment]
Doing some cleanup, feel free to reopen if needed.

**Comment by gisostallenberg** [comment]
> I use typescript in my projects these days, but haven't contributed types to a public project. If I get the types fleshed out for my project, I'll be sure to package them up as a a PR.

@toddsampson did you actually create the types files?
