### ISSUE TITLE
Best practice for translating labels?

### ISSUE THREAD

**Issue by gnilebat** [koumoul-dev/vuetify-jsonschema-form#81]
Hey, love the library. 
Is there a way to translate the generated labels? I have the Vuetify i18n implementation setup and passing it to the library. The only thing missing is the labels for the generated forms. Could the slots be used for that, if yes how? 
Thanks in advance

**Comment by gnilebat** [comment]
Alright thanks for the quick answer. I look into the first idea and also think about converting the schema into a different language. Problem is I would also have to convert it back before sending it to the api of course.

**Comment by albanm** [comment]
I just published a small release with a little discussion of the topic in [the documentation](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#localization).

I also implemented a simple replacement in resolved json refs, \~$locale~\ is replaced with the current locale. I don't know if it is a worthy solution, but it doesn't cost me anything and it might help somehow.

**Comment by gnilebat** [comment]
Just a small update from me, for now I am just going through the properties of my schema Object and replace all the titles with the 18n t function.  Kind of like this:
```    
 for (
        let index = 0;
        index < Object.keys(this.schema.properties).length;
        index++
      ) {
        const property = Object.keys(this.schema.properties)[index];
        this.schema.properties[property].title = this.$vuetify.lang.t(`$vuetify.entityKeys.${property}`);
      }
```
