### ISSUE TITLE
Migrating from 0.x to 1.x x-display slots

### ISSUE THREAD

**Issue by jousepo** [koumoul-dev/vuetify-jsonschema-form#84]
Hi!!!
I've a problem with my custom slots that i've working in 0.x version.
1.x examples only have per properties slots but not x-display examples. Is this working as earlier version?
Were can i found an updated example for this functionality?

Here the slots 0.x demo of yours: https://koumoul-dev.github.io/vuetify-jsonschema-form/0.x/?example=slots

This is an example of one of my custom slots:

`<template slot="custom-radiobuttons" slot-scope="{ fullSchema }">
        <label>{{ fullSchema.title }}</label>
        <v-tooltip v-if="fullSchema.description" bottom open-on-click>
          <template v-slot:activator="{ on }">
            <v-avatar size="22" style="background-color:rgba(0, 0, 0, 0.54);" v-on="on">
              <small class="bold-font white--text">i</small>
            </v-avatar>
          </template>
          <span>{{ fullSchema.description }}</span>
        </v-tooltip>
        <v-btn-toggle
          v-model="innerModel[fullSchema.key]"
          :multiple="fullSchema.multiple"
        >
          <v-btn
            v-for="opt in fullSchema.enum"
            :key="opt.value"
            :value="opt.value"
            small
          >
            {{ opt.name }}
          </v-btn>
        </v-btn-toggle>
      </template>`

**Comment by albanm** [comment]
Indeed there was a regression, it should be fixed in v1.5.2.  I also completed the [slots example](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#slots) in the doc.

**Comment by jousepo** [comment]
Thank you for your great effort!!!
