### ISSUE TITLE
Is it possible to add custom attributes?

### ISSUE THREAD

**Issue by majkelch** [koumoul-dev/vuetify-jsonschema-form#85]
Hello,
is it possible to add custom attributes?, eg:
```
 <p data-attribute="myData">...</p>
```

**Comment by albanm** [comment]
No, it is not possible at the moment. You can define props passed to some of the vuetify components, but not html attrs.

What can be done is injecting any html code before, after and in place of the properties [using slots](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#slots). I don't know if this can help.

**Comment by majkelch** [comment]
@albanm Thank you for the answer, I am going to think about this.
