### ISSUE TITLE
Bug in arrays?

### ISSUE THREAD

**Issue by OdiljonQurbon** [koumoul-dev/vuetify-jsonschema-form#86]
I think there is a bug with arrays.
To reproduce: 
1. Open Tuples example https://codepen.io/pen/?editors=1010
2. Type some text into both string fields
![image](https://user-images.githubusercontent.com/54809428/81092609-852cba00-8f09-11ea-8486-a0ec144de406.png)
3. Start to delete the text in the first field.
4. Bug: when you delete all chars the text from the second field is moved into the first field
 
![image](https://user-images.githubusercontent.com/54809428/81092979-1734c280-8f0a-11ea-8850-424c770b6793.png)

**Comment by albanm** [comment]
Thanks for the detailed report, this is fixed in v1.5.1.
