### ISSUE TITLE
Generation of ids

### ISSUE THREAD

**Issue by jhhammer** [koumoul-dev/vuetify-jsonschema-form#87]
Is there any possibility to add the generation of ids for the used form elements based on the names in the schema? That would make it much easier to use selenium on the forms.

**Comment by albanm** [comment]
I just released 1.6.0 with this, it will be better for the internal test cases of the library as well.

I also added a idPrefix option to let the user manage potential id conflicts.

**Comment by jhhammer** [comment]
That was quick! Thank you very much!
