### ISSUE TITLE
Missing Radio button definitions

### ISSUE THREAD

**Issue by razorfever** [koumoul-dev/vuetify-jsonschema-form#88]
Hello and thanks for a great plugin! Loving it so far.

One bug I stumbled upon though:
VRadio and VRadioGroup seem to be missing from the Vuetify component definitions in VJsf.js. This results in `x-display: radio` not working as intended.

**Comment by albanm** [comment]
I accepted a pull request a few weeks ago with support for radio buttons and checkboxes. But the example is hidden as I still need to review the code and the functionality more closely. I wouldn't call it a bug, but an unfinished/undocumented feature :)

**Comment by albanm** [comment]
please see https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#selection-controls
