### ISSUE TITLE
Problem subschema in editable array

### ISSUE THREAD

**Issue by jhhammer** [koumoul-dev/vuetify-jsonschema-form#90]
I am trying to use subschemes `checks.objectArrayProp.oneOf` in an editable array `checks`. The schema is shown at the end.

When using this with 
```
   "@koumoul/vuetify-jsonschema-form": "^0.36.4",
```
and clicking the "+"-Button, another v-card containing the subschema is directly added showing the contents. When using
```
    "@koumoul/vjsf": "^1.6.0",
```
and clicking the "+"-button, a dialog appears, where I can choose between the subschemes, but when clicking the "OK"-button, a v-card for the item is shown but without its content and the following errors are shown in the console:
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Invalid prop: type check failed for prop "schema". Expected Object, got Undefined 
```
and
```
Error in callback for immediate watcher "rawSelectItems": "SyntaxError: Unexpected token u in JSON at position 0"
```
and
```
Error in callback for immediate watcher "fullSchema": "SyntaxError: Unexpected token u in JSON at position 0"
```
and
```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.o.prepareFullSchema
```
Somebody knows what the problem is?

The schema looks like this:
```
schema: {
        "type": "object",
        "properties": {
            "checks": {
                "type": "object",
                "title": "Checks",
                "description": "",
                "properties": {
                    "objectArrayProp": {
                        "type": "array",
                        "title": "array of objects",
                        "description": "This description is used as a help message.",
                        "x-itemTitle": "schemaKey",
                        "items": {
                            "type": "object",
                            "title": "Select a sub-schema",
                            "oneOf": [
                                {
                                    "type": "schema",
                                    "title": "sub-schema",
                                    "properties": {
                                        "schemaKey": {
                                            "type": "string",
                                            "const": "subSchema1"
                                        },
                                        "stringProp1": {
                                            "type": "string",
                                            "title": "I'm a property in sub-schema 1"
                                        },
                                        "stringProp2": {
                                            "type": "string",
                                            "title": "I'm another property in sub-schema 1"
                                        }
                                    }
                                },
                                {
                                    "type": "schema",
                                    "title": "another sub-schema",
                                    "properties": {
                                        "schemaKey": {
                                            "type": "string",
                                            "const": "subSchema2"
                                        },
                                        "numberProp2": {
                                            "type": "number",
                                            "title": "I'm a property in sub-schema 2"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    }
```

**Comment by jhhammer** [comment]
In `EditableArray.js` I changed the method `readonlyItemSchema()` to support `oneOf`:
```javascript
    readonlyItemSchema() {
      if (!this.fullSchema.items || (!this.fullSchema.items.properties && !this.fullSchema.items.oneOf)) {
        window.console.error("readonlyItemSchema() | returning nothing")
        return
      }
      
      const schema = JSON.parse(JSON.stringify(this.fullSchema.items))
      schema.readOnly = true
      if (this.itemTitle) {
        if (this.fullSchema.items.properties){
          delete schema.properties[this.itemTitle]
        } else if (this.fullSchema.items.oneOf){
          schema.oneOf.forEach((value)=>{
            delete value.properties[this.itemTitle]
          });
        }
      }

      return schema
    }
```
This fixes the problem that the subschema wasn't shown in the draggable list.

Furthermore, I added the `fullOptions.objectContainerClass` values to the `class` when the `v-container` is created in `renderEditableArray(h)` by changing
```javascript
        list = h('v-container', { props: { gridListMd: true }, class: 'pt-0 px-2' }, [
```
to
```javascript
        list = h('v-container', { props: { gridListMd: true }, class: 'pt-0 px-2 ' + this.fullOptions.objectContainerClass}, [
```
to make it possible to influence the rendering that container. May be a varialbe editableArrayContainerClass should be used instead?

**Comment by jhhammer** [comment]
I am currently working on the problem that the values contained in the draggables aren't updated. If I now edit an element of the array, the model is updated correctly but the content in the draggables isn't updated. Any idea?

**Comment by albanm** [comment]
Could you make this fix into a pull request ? If possible update an example to illustrate it and prevent future regressions.

I didn't understand the bug you described with draggable. If you are working on it that's fine, if you hit a roadblock maybe you could describe it more precisely in another ticket with an example and I will take it from there.

**Comment by jhhammer** [comment]
I am currently working on an example but I need to make it run in a docker container. I have almost succeeded but now I am facing the problem, that I cannot add an example. I thought it should be quite easy by just copying e.g. `examples/basic.js` to `examples/basic2.js` and changing the id and the title. Am I missing something?

**Comment by jhhammer** [comment]
I am currently working on a descriptions for newbies like me how to add examples using docker. I will add a pull request for my docker stuff in a few minutes. After that I will add an example especially for this issue.

**Comment by jhhammer** [comment]
I added an example demonstrating the bug. You can find it as `/examples#editableArrayWithSubschemes` in commit `36daa6b6be8ce1ab3356914a465eed8d71710be5` of https://github.com/jhhammer/vuetify-jsonschema-form.git

I had already described a maybe first fix above. Then the draggables are shown but after editing the read only area is not updated.

**Comment by jhhammer** [comment]
I have fixed this problem and will create a pull request containing the example.

**Comment by jhhammer** [comment]
The pull request is #102: 

I added an example demonstrating the bug. You can find it as /examples#editableArrayWithSubschemes in jhhammer@3218a59.

The fixes for showing the read only areas and making them update after editing can be found in jhhammer@b9779b2.

**Comment by albanm** [comment]
I worked on this in the current release, using your pull request as starting point. It was before some vacations so things are a bit fuzzy, but I think it is fixed.If you could check that everything works for you it would be great.

**Comment by jhhammer** [comment]
Great, no problem found!
