### ISSUE TITLE
Time picker display in 24hr format

### ISSUE THREAD

**Issue by pachr** [koumoul-dev/vuetify-jsonschema-form#95]
Hi,

Thank you for the awesome job on this module ! It saves a lot of time in development.
I am just facing a problem with vuetify time picker display and vuetify-jsonschema-form. 

I am not able to change time picker format in `24hr`, I am talking about the vuetify component 'props' as indicated here : https://codepen.io/pachr/pen/MWaMezL

I have tried many things with vuetify-jsonschema-form:
- Set time format as indicated here in the documentation : https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/configuration (with `hour12: false` in `toLocalTimeString()` function according to : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString ). But this option  only results in a change in the input not the component's display

- Set a `x-props` directly in the json schema, it does not work

- Change locale to `fr`, it does not work

You can see my tries here : 

https://codepen.io/pachr/pen/bGVPemv

My results:
- Great display in the input
![image](https://user-images.githubusercontent.com/11092139/83134469-b487ae80-a0e4-11ea-96e7-8fe3299e64f5.png)

- Bad display in the time picker:
![image](https://user-images.githubusercontent.com/11092139/83134591-e1d45c80-a0e4-11ea-8d68-96e487da41d9.png)

What I want:
https://codepen.io/pachr/pen/MWaMezL

By adding `format: '24hr'` in your DateProperty mixins (https://github.com/koumoul-dev/vuetify-jsonschema-form/blob/master/lib/mixins/DateProperty.js#L71) it seems to do the job 

Am I doing something wrong? Could you help with that? :)

**Comment by pachr** [comment]
@albanm Thanks a lot for your quick answer and quick fix ! It works well from my side after updating this module with NPM.

Just one last question about time and date picker, is possible to add `slots` as explain in vuetify documentation here : https://vuetifyjs.com/fr-FR/components/time-pickers/

In order to add action buttons (OK and Cancel) below the clock? (I can open an other issue if it's no longer related with my first question)

**Comment by albanm** [comment]
Yes, please open another ticket. I will have a look sometime in the next few days.
