### ISSUE TITLE
Is it possible to include an image by using x-slot :{before'} ?

### ISSUE THREAD

**Issue by selobu** [koumoul-dev/vuetify-jsonschema-form#98]
Hi, some kind of questions could include an image as a description so it would be nice if possible to include a url or equivalent to display it.

For example

"x-slot":{before:'imageurl'}    or in a general way 

 "x-slot":{before:'html_code_to_render'}

**Comment by selobu** [comment]
example
Example

stringProp: {
			type: 'string',
			title: 'I\'m a string',
			description: 'This description is used as a help message.',
      "x-slots":{ beforehtml : '<v-img src="https://i5.walmartimages.com/asr/5893b3f3-4d07-4633-953c-9c9e6e0fed1d_1.0002dc3c1c6d11007f3b2a71bc454f9e.jpeg"></v-img>'}
		}

**Comment by albanm** [comment]
The before slot is passed to the markdown parser (see the markdown option in [configuration doc] (https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/configuration)).

If your markdown parser supports embedded HTML content then you can already use HTML content in the before slot. If you don't use a markdown parser, the lib will simply put the textual content as HTML content, so it works also.

**Comment by selobu** [comment]
I try it but it's not working. 
check this[ pen ](https://codepen.io/Selobu/pen/XWXrWMq)

**Comment by albanm** [comment]
Thanks for the pull request, but I think this is better solved by simply using markdown render options.

It was already possible to define a custom markdown renderer using the "markdown" option, but I just made it easier with the "markdownit" option. See [this example](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#slots) and its options \`{  "markdownit": { "html": true  }}\`.
